### ISSUE TITLE
"Invalid audio channel count" Can not run my file.flac

### ISSUE THREAD

**Issue by mariohandsome** [GoogleCloudPlatform/php-docs-samples#1006]
I run success the data test (test/data/audio32KHz.flac) But when I run my file, it alern error:
.
Success with demo:
.
PS C:\xampp\htdocs\speech\speech-16\speech> php src/transcribe_sync.php test/data/audio32KHz.flac
Transcript: how old is the Brooklyn Bridge
Confidence: 0.9849156
.
Error when run my file.flac:
.
PS C:\xampp\htdocs\speech\speech-16\speech> php src/transcribe_sync.php test/data/quick32KHz.flac
PHP Fatal error:  Uncaught Google\ApiCore\ApiException: {
    "message": "Invalid audio channel count",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": []
}

  thrown in C:\xampp\htdocs\speech\speech-16\speech\vendor\google\gax\src\ApiException.php on line 139

Fatal error: Uncaught Google\ApiCore\ApiException: {
    "message": "Invalid audio channel count",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": []
}

  thrown in C:\xampp\htdocs\speech\speech-16\speech\vendor\google\gax\src\ApiException.php on line 139
.
.
My file here: https://drive.google.com/open?id=1QTnlICPXiexSNdDeYWfrm86Bps_e0ki3

**Comment by bshaffer** [comment]
Looks like you have two options, 

1. Convert your audio to a [single channel](https://trac.ffmpeg.org/wiki/AudioChannelManipulation)
2. Configure the API request to use [multiple channels](https://cloud.google.com/speech-to-text/docs/multi-channel)

You can enable multiple channels on the `RecognitionConfig` object:

```php
// set config
$config = (new RecognitionConfig())
    ->setEncoding($encoding)
    ->setSampleRateHertz($sampleRateHertz)
    ->setLanguageCode($languageCode)
    // configure for multiple channels
    ->setAudioChannelCount(2)
    ->setEnableSeparateRecognitionPerChannel(true);
```

Here is the full example for enabling multiple channels:

```php
use Google\Cloud\Speech\V1\SpeechClient;
use Google\Cloud\Speech\V1\RecognitionAudio;
use Google\Cloud\Speech\V1\RecognitionConfig;
use Google\Cloud\Speech\V1\RecognitionConfig\AudioEncoding;

$audioFile = 'path to an audio file';

// change these variables if necessary
$encoding = AudioEncoding::LINEAR16;
$sampleRateHertz = 32000;
$languageCode = 'en-US';

// get contents of a file into a string
$content = file_get_contents($audioFile);

// set string as audio content
$audio = (new RecognitionAudio())
    ->setContent($content);

// set config
$config = (new RecognitionConfig())
    ->setEncoding($encoding)
    ->setSampleRateHertz($sampleRateHertz)
    ->setLanguageCode($languageCode)
    // configure for multiple channels
    ->setAudioChannelCount(2)
    ->setEnableSeparateRecognitionPerChannel(true);

// create the speech client
$client = new SpeechClient();

try {
    $response = $client->recognize($config, $audio);
    foreach ($response->getResults() as $result) {
        $alternatives = $result->getAlternatives();
        $mostLikely = $alternatives[0];
        $transcript = $mostLikely->getTranscript();
        $confidence = $mostLikely->getConfidence();
        printf('Transcript: %s' . PHP_EOL, $transcript);
        printf('Confidence: %s' . PHP_EOL, $confidence);
    }
} finally {
    $client->close();
}
```
