### ISSUE TITLE
Symfony example does not write an error-report

### ISSUE THREAD

**Issue by do-web** [GoogleCloudPlatform/php-docs-samples#1012]
My application is not hosted on google cloud but i want to use the error reporting and logging in google cloud. The logging works, but the error-reporting not. The subscriber called on an 500 Exception but nothing are logged in error-reporting. Have anyone an idea whats wrong here?

**Comment by do-web** [comment]
It seems the version and the serivce is not set. How and where do i set the metadata in the symfony app?

**Comment by bshaffer** [comment]
I've made some updates to the symfony example ([see here](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1033/files#diff-6f66a6e880f6242c5f5eb97b9552c2e6)) that may fix your issue. Try incorporating these changes, and if that doesn't work, try printing the debugging the 500 being thrown, as there is probably a legitimate error being obfuscated.
