### ISSUE TITLE
Trying to build a small translate function which translates and outputs in englih spellings

### ISSUE THREAD

**Issue by vidyatshree** [GoogleCloudPlatform/php-docs-samples#1013]
Hi Team,

I am trying to write a function where i will be hitting your translate api for every row in my excel sheet and then outputting the translated word in english rather than in its language.

A quick help and suggestion on this will help a lot.

Thanks in advance.

Warm regards,
Vidya.t
tvidyashree5@gmail.com
![Selection_005](https://user-images.githubusercontent.com/45627194/72886663-3aa77900-3d30-11ea-85b6-a5ec219ea95b.png)

**Comment by tbpg** [comment]
Here is a tutorial for how to build an application that translates text with PHP: https://cloud.google.com/php/getting-started/background-processing

For doing it in a spreadsheet, you might want to use the Sheets API or do something directly in the spreadsheet. I'm not sure.

This repo is used for the PHP samples embedded in cloud.google.com. So, it's not the best place to ask questions like this. If you ask on StackOverflow, more people will see the question and be able to help. More people will also be able to discover the question if they are having a similar problem. So, I'm going to close this.
