### ISSUE TITLE
Add documentation and example about mail sending for Symfony

### ISSUE THREAD

**Issue by Sethbass** [GoogleCloudPlatform/php-docs-samples#1021]
Hi @bshaffer , 

As discussed, we need to add more documentation about the way to send emails with Symfony on GAE.
Good news is that I already know how to do that and I use this method on several live projects.
Second good news, Symfony documentation is also pretty clear about it.
So the ambition here is not to rewrite Symfony documentation but only to make the point clear about the recommended way to send emails with Symfony on GAE for PHP 7.x.

Thanks a lot,

Sebastien

**Comment by bshaffer** [comment]
Added in #1030
