### ISSUE TITLE
this is total crap it dont work it wastes my time

### ISSUE THREAD

**Issue by jamieduk** [GoogleCloudPlatform/php-docs-samples#1024]
v1 looked good till you all stopped it and moved to v2 which is bloated crap that fails! i dont want to require credentials for it to work i shouldn't need any prerequisites either just work! why is this not simple

**Comment by bshaffer** [comment]
We are sorry to hear you are having a hard time with our samples. I am not sure what you are referring to with regards to v1 and v2, but I assume you mean the [google/apiclient](https://GitHub.com/googleapis/google-api-php-client)? 

If you have a question or are encountering an error, please reply with that and we can assist you.
