### ISSUE TITLE
How to set path to composer in app.yaml file

### ISSUE THREAD

**Issue by eliadjoke** [GoogleCloudPlatform/php-docs-samples#1029]
After going throw the [docs](https://cloud.google.com/appengine/docs/standard/php7/config/appref ) I didn't find anything related to setting a path to composer file and was wondering if that is possible.

**Comment by bshaffer** [comment]
Hello @eliadjoke !

Unfortunately, `composer.json` must live in the root of your application. What is the use-case for having it live elsewhere? 

If you use Cloud Run, you can define a custom `Dockerfile` and change this, but it would add a lot of complexity if not absolutely needed.
