### ISSUE TITLE
Symfony Tutorial : Add PDOSessionHandler and Upload tutorial

### ISSUE THREAD

**Issue by Sethbass** [GoogleCloudPlatform/php-docs-samples#1039]
Hello @bshaffer ,

I will create 2 tutorials : 
* How to solve the issue with the sessions
* How to upload a file

Is that OK on your end ?

Cheers,

**Comment by Sethbass** [comment]
@bshaffer, I have submitted a new pull request and as usual it is stuck because of old commits. Can you please have a look ?

**Comment by bshaffer** [comment]
Closing this since we can track this in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1040
