### ISSUE TITLE
longRunningRecognize and pollUntilComplete doesn't work with really long files

### ISSUE THREAD

**Issue by iglesiaspablo** [GoogleCloudPlatform/php-docs-samples#1094]
I'm using this code https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech/src/transcribe_async_gcs.php to upload and transcribe a 1 hour audio file, and the `$operation->pollUntilComplete();` function ends but both `$operation->operationSucceeded()` and `$operation->operationFailed()` are `false`, and `$operation->getError()` is empty.

Tested it in multiple platforms, always using the options to transcribe the file from a Google Cloud Storage bucket. Same code for other audio lengths works correctly.

**Comment by bshaffer** [comment]
@iglesiaspablo A few things to try here:

1. What is the return of `pollUntilComplete`?
1. Do you know if your PHP environment has the `grpc.so` PHP extension installed? You can find this out by running `php -i | grep grpc` and seeing if there is any config output.

2. If you're using REST instead of gRPC, try seeing the result from the API. It's possible some important response is getting buried

**Comment by bshaffer** [comment]
It's possible that because the audio file is so long (1 hour), the `pollUntilComplete` function hits a quota limit. Although I'd expect this to show up in `getError`

**Comment by iglesiaspablo** [comment]
Hi @bshaffer. I'll answer according to the numbers you posted in your reply:

1. `$operation->pollUntilComplete()` return is `false`. `$operation->operationSucceeded()` return is `false`. `$operation->getResult()` is `null`. `$operation->operationFailed()` return is `false`. `$operation->getError()` is `null`.

2. `php -i | grep grpc` result is `Additional .ini files parsed => /etc/php/conf.d/grpc.ini,` so I think I'm using it.

3. I'm not sure how to check which one I'm using. Is there a way to be sure of that?

Regarding the other message, I'm not seeing any quota errors in the console, and every other operation I'm running with files that aren't that long is successful. Is there a way to get error logs or something like that for the operations that aren't successful?

**Comment by sgreenberg** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
