### ISSUE TITLE
Wordpress "document_root" issue

### ISSUE THREAD

**Issue by dknesek** [GoogleCloudPlatform/php-docs-samples#110]
The generated app.yaml looks like this:

runtime: custom
vm: true

beta_settings:
  cloud_sql_instances: PROJECT_NAME:us-central1:wp

runtime_config:
  document_root: wordpress

Error

> Beginning deployment...
ERROR: (gcloud.preview.app.deploy) Unknown runtime_config entry : document_root.

**Comment by tmatsuo** [comment]
Thanks for reporting. I'll fix this. For a workaround, can you change it to `runtime: php`?

(Embarrassingly our tests are not running for that directory.)
