### ISSUE TITLE
Multiple tasks

### ISSUE THREAD

**Issue by alissonlinneker** [GoogleCloudPlatform/php-docs-samples#1111]
How to send multiple tasks on same request?

No example has been able to demonstrate. I need to send thousands of tasks in a single request.
Currently the task is slow in synchronous mode.

**Comment by averikitsch** [comment]
Currently we do not support bulk task enqueueing. For feature requests to the underlying service, we recommend you file an issue in their public issue tracker. You can find that  https://issuetracker.google.com/issues/new?component=608118&template=0. Using multithreading could improve performance, but at this time we do not have the capability to provide an example.
