### ISSUE TITLE
The PHP version of Firestore increment doesn't work

### ISSUE THREAD

**Issue by jmg460** [GoogleCloudPlatform/php-docs-samples#1119]
In php-docs-samples/firestore/src/update_doc_increment.php, the word increment on line 46 is speled wrong. 'incremet' should be 'increment'.  The actual code also doesn't work for me even with the correct spelling, but that could be my configuration.  In any case, the speling should be updated.

**Comment by bshaffer** [comment]
Fixed in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1121

**Comment by jmg460** [comment]
Fix is confirmed. The increment method is also working for me now. I don't know if it was a fix in my code or your end.  In any case, thank you!
