### ISSUE TITLE
Php-docs-samples require migraion to split health 

### ISSUE THREAD

**Issue by AlexanderChupin** [GoogleCloudPlatform/php-docs-samples#1140]
When trying to deploy the Php-docs-sample in GAE flex enfironment https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/logging I'm getting the following error:

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Legacy health checks are no longer supported for the App Engine Flexible environment. This app's feature setting is configured to use legacy health checks by default. For instructions on migratin
g to split health checks see https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks

Migration can be done by adding the following snippet to the **app.yaml**
`liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 5
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 180`

and adding **nginx-app.conf** to the project root with the following content
`location ^~ /liveness_check {
    access_log off;
    return 200 'ok';
}

location ^~ /readiness_check {
    access_log off;
    return 200 'ok';
}`

**Comment by bshaffer** [comment]
The samples here work for new projects. If you are working with an older project that does not have split health checks enabled, you'll need to migrate using the steps supplied in the [Migrating from legacy health checks](https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks) guide. If you are not worried about downtime with existing services, you can simply run the following command to configure split health checks:

```
gcloud app update --split-health-checks --project
```
