### ISSUE TITLE
PHP API not working at all

### ISSUE THREAD

**Issue by LoekvanKooten** [GoogleCloudPlatform/php-docs-samples#1141]
This is what I get:

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 500 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:207 Stack trace: #0 C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(162): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(109): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(30): GuzzleH in C:\xampp\htdocs\ModernMT\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 207`

This happens right after:

```
# Instantiates a client
$client = new SpeechClient();
```

**Comment by bshaffer** [comment]
It seems like you are having networking issues. It's possible you have a proxy client running (such as Charles Web Proxy) or something else which is creating timeouts on outgoing calls.

**Comment by LoekvanKooten** [comment]
No, this turned out to be a bug in GuzzleHTTP. See https://github.com/googleapis/google-cloud-php/issues/3254#issuecomment-665076372

**Comment by bshaffer** [comment]
Great! thank you for reporting this. I'm glad we were able to get this resolved.
