### ISSUE TITLE
Authentication Example for ImageAnnotatorClient

### ISSUE THREAD

**Issue by yosun** [GoogleCloudPlatform/php-docs-samples#1151]
Is there an example snippet on how to authenticate for ImageAnnotatorClient? The general authentication documentation do not seem to help here as it is not clear where to pass the authentication file to. (Previously for VisionClient, you can just pass the authentication file in on creation)

**Comment by dwsupplee** [comment]
Hi @yosun 👋 ,

We have a section [about authentication](https://github.com/googleapis/google-cloud-php/blob/d411262f0574cdb31deb56bb7cb39d9ead878c2a/AUTHENTICATION.md#client-authentication) over on the google-cloud-php repository. The `VisionClient` I believe you were using was a handwritten client, whereas the `ImageAnnotatorClient` is generated. For generated clients the authentication flow is slightly different, you can use the `credentials` option when constructing the client:
```php
$client = new ImageAnnotatorClient([
    'credentials' => '/path/to/key/file.json'
]);
```
