### ISSUE TITLE
Permission Error Stackdriver Logging Laravel on App Engine Standard

### ISSUE THREAD

**Issue by neysi** [GoogleCloudPlatform/php-docs-samples#1176]
Hello, 
I followed the tutorial from https://cloud.google.com/community/tutorials/run-laravel-on-appengine-standard

But the logging and error reporting doesn't work.

{
"error": {
"code": 403,
"message": "The caller does not have permission",
"status": "PERMISSION_DENIED"
}
}

I am using  "laravel/framework": "^7.0"

Thank you

**Comment by bshaffer** [comment]
Hello! Could you provide me with a little more information? Where are you seeing this error? Does it show up in the logs, or when you deploy? Can you give a stack trace?

**Comment by bshaffer** [comment]
This is interesting, is it possible you added a `credentials.json` file or specified credentials to the Laravel application which are not the default credentials?

**Comment by netwons** [comment]
not work
error
{ "message": "This API method requires billing to be enabled. Please enable billing on project #1051023892108 by visiting https:\/\/console.developers.google.com\/billing\/enable?project=1051023892108 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.", "code": 7, "status": "PERMISSION_DENIED", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.rpc.Help" }, { "@type": 0, "data": [ { "description": "Google developers console billing", "url": "https:\/\/console.developers.google.com\/billing\/enable?project=1051023892108" } ] }, { "@type": 1, "data": "type.googleapis.com\/google.rpc.ErrorInfo" }, { "@type": 1, "data": "BILLING_DISABLED" }, { "@type": 1, "data": "googleapis.com" }, { "@type": 1, "data": { "service": "vision.googleapis.com", "consumer": "projects\/1051023892108" } } ] }
im api enabled
### code in laravel
```
$imageAnnotator = new ImageAnnotatorClient([
            'credentials'=>"1.json"
        ]);
        $path="2.png";
        $image = file_get_contents($path);
	    $response = $imageAnnotator->textDetection($image);
	    $texts = $response->getTextAnnotations();

	    printf('%d texts found:' . PHP_EOL, count($texts));
	    foreach ($texts as $text) {
	        print($text->getDescription() . PHP_EOL);

	        # get bounds
	        $vertices = $text->getBoundingPoly()->getVertices();
	        $bounds = [];
	        foreach ($vertices as $vertex) {
	            $bounds[] = sprintf('(%d,%d)', $vertex->getX(), $vertex->getY());
	        }
	        print('Bounds: ' . join(', ', $bounds) . PHP_EOL);
	    }

	    $imageAnnotator->close();
```

**Comment by netwons** [comment]
i activated but not billing

**Comment by bhaidar** [comment]
Was there any solution to this problem? I am facing something similar now. Thanks

**Comment by AbokiNapoli** [comment]
Hello @bshaffer 
what is the fix to this error?

**Comment by meredithslota** [comment]
The error message seen instructs users to create a billing account, as it is required for this API method. The links in the error go to the specific project, so you should see similar guidance if you are encountering a similar error. If folks are seeing a different error, please file a new issue. Thanks!
