### ISSUE TITLE
Pub/Sub: please add DLQ samples for Pub/Sub

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/php-docs-samples#1178]
Please add samples for 

1. create a subscription with a dead letter policy: `pubsub_dead_letter_create_subscription`
1. update a subscription's dead letter policy: `pubsub_dead_letter_update_subscription`
1. remove a subscription's dead letter policy: `pubsub_dead_letter_remove`
1. show the delivery attempt field in received messages: `pubsub_dead_letter_delivery_attempt`

See existing [Java](https://github.com/googleapis/java-pubsub/tree/master/samples/snippets/src/main/java/pubsub), [Go](https://github.com/GoogleCloudPlatform/golang-samples/pull/1279), [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3904), [Node](https://github.com/googleapis/nodejs-pubsub/pull/1010) samples.

**Comment by anguillanneuf** [comment]
Is this work still being planned?

**Comment by jdpedrie** [comment]
Thanks for the reminder, and sorry for the delay. This sorta fell off my radar. I'm working on it today.
