### ISSUE TITLE
$snapshot object does not exist

### ISSUE THREAD

**Issue by appbytes** [GoogleCloudPlatform/php-docs-samples#1192]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/eec5f5ca0c7757a9ef7afaeeeaa3c60228393f44/firestore/src/get_multiple_docs.php#L50

**Comment by bshaffer** [comment]
Closing because of a lack of description. Please open a new issue and describe what you did, what happened as a result, and what you expect to happen
