### ISSUE TITLE
Where api_key should I enter?

### ISSUE THREAD

**Issue by netwons** [GoogleCloudPlatform/php-docs-samples#1233]
Where api_key should I enter?

**Comment by netwons** [comment]
**Setting up authentication**

> In the Cloud Console, go to the Create service account key page.
> Go to the Create Service Account Key page
> From the Service account list, select New service account.
> In the Service account name field, enter a name.
> Don't select a value from the Role list. No role is required to access this service.
> Click Create. A note appears, warning that this service account has no role.
> Click Create without role. A JSON file that contains your key downloads to your computer.

### next
**export GOOGLE_APPLICATION_CREDENTIALS="[PATH].json"**

**Comment by bshaffer** [comment]
Looks like you figured it out!
