### ISSUE TITLE
not work api 

### ISSUE THREAD

**Issue by netwons** [GoogleCloudPlatform/php-docs-samples#1235]
**not work
error**
`{ "message": "This API method requires billing to be enabled. Please enable billing on project #1051023892108 by visiting https:\/\/console.developers.google.com\/billing\/enable?project=1051023892108 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.", "code": 7, "status": "PERMISSION_DENIED", "details": [ { "@type": 0, "data": "type.googleapis.com\/google.rpc.Help" }, { "@type": 0, "data": [ { "description": "Google developers console billing", "url": "https:\/\/console.developers.google.com\/billing\/enable?project=1051023892108" } ] }, { "@type": 1, "data": "type.googleapis.com\/google.rpc.ErrorInfo" }, { "@type": 1, "data": "BILLING_DISABLED" }, { "@type": 1, "data": "googleapis.com" }, { "@type": 1, "data": { "service": "vision.googleapis.com", "consumer": "projects\/1051023892108" } } ] }`
**im api enabled**

this code in laravel
 ```
 $imageAnnotator = new ImageAnnotatorClient([
            'credentials'=>"1.json"
        ]);
        $path="2.png";
        $image = file_get_contents($path);
	    $response = $imageAnnotator->textDetection($image);
	    $texts = $response->getTextAnnotations();

	    printf('%d texts found:' . PHP_EOL, count($texts));
	    foreach ($texts as $text) {
	        print($text->getDescription() . PHP_EOL);

	        # get bounds
	        $vertices = $text->getBoundingPoly()->getVertices();
	        $bounds = [];
	        foreach ($vertices as $vertex) {
	            $bounds[] = sprintf('(%d,%d)', $vertex->getX(), $vertex->getY());
	        }
	        print('Bounds: ' . join(', ', $bounds) . PHP_EOL);
	    }

	    $imageAnnotator->close();
```

**Comment by netwons** [comment]
is there google vision

**Comment by bshaffer** [comment]
Try enabling billing on your project by visiting https://console.developers.google.com/billing/enable?project=1051023892108
