### ISSUE TITLE
🐑 functions: Refactor PHP samples

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/php-docs-samples#1271]
This is an issue tracking all requested refactors of Cloud Functions PHP samples.

- [x] Add start scripts to `composer.json`
- [x] Use trait-based `request` method instead of raw `POST`s in integration tests (e.g. `$this->client->request('POST'` --> `$this->request(CloudEvent::fromArray($cloudevent));`)
- [x] Use `processFunctionLogs` helper.
- [x] **New:** Replace `assertContains()` with `assertStringContainsString()`

**Comment by ace-n** [comment]
@grayside @bshaffer these seem like "nice-to-haves" that the Serverless team isn't staffed for. Can we close this issue?

cc @iennae

**Comment by ace-n** [comment]
Looks like #1269 fixed the last point (`assertStringContainsString`)

**Comment by ace-n** [comment]
RE **point 2** - do we want to use the [`php-tools` repo](https://github.com/GoogleCloudPlatform/php-tools) in public facing samples? (Namely, sample tests that show users how to _test_ their PHP Cloud Functions.)

(The alternative is we keep them as-is, and ignore that request for those.)

**Pros**
* The PHP tools repo has useful helper functions
* The implementation looks cleaner with these helper functions ("syntactic sugar")

**Cons**
* Using this repo adds another dependency
* We'd have to maintain this repo at a similar level as the samples themselves

**Recommendation**
Drop the `php-tools` library, and keep the `Sample*Test.php` files as-is.

**Comment by bshaffer** [comment]
> do we want to use the [`php-tools` repo](https://github.com/GoogleCloudPlatform/php-tools) in public facing samples?

This is a bit late, but just for posterity, we definitely do NOT want `php-tools` to be used by customers. It's bloated and not maintained. The correct decision was made here!
