### ISSUE TITLE
Symfony app engine standard - monolog 

### ISSUE THREAD

**Issue by chuckchick** [GoogleCloudPlatform/php-docs-samples#1295]
Where can I see the 'google_cloud' monolog handler below used?    
To me it seems whether it's there or not the result is the same for me.

When an uncaught exception is hit, I do see the error report in the GCP console but that happens even without the   'google_cloud: ' section.      

[https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/symfony-framework/config/packages/prod/monolog.yaml](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/symfony-framework/config/packages/prod/monolog.yaml)

        google_cloud:
            type: service
            id: monolog_psr_batch_logger

My Full File:

	monolog:

	  handlers:

		main:
		  type: fingers_crossed
		  action_level: error
		  handler: grouped
		  excluded_http_codes: [ { 403: [ '^/user', '^/admin' ] }, { 404: [ '^/' ] }, { 405: [ '^/' ] } ]

		grouped:
		  type: group
		  members: [ streamed, deduplicated ]

		streamed:
		  type: stream
		  path: "%kernel.logs_dir%/%kernel.environment%.log"
		  level: info

		console:
		  type: console
		  process_psr_3_messages: false
		  channels: [ "!event", "!doctrine" ]

		deduplicated:
		  type: deduplication
		  handler: email_developer

		email_developer:
		  # https://symfony.com/doc/current/logging/monolog_email.html
		  type: symfony_mailer
		  from_email: 'hello@myprojectxxx.com'
		  to_email: 'tech@myprojectxxx.com'
		  subject: 'Error: %%message%%'
		  level: debug
		  formatter: monolog.formatter.html
		  headers: [ 'Content-Type: text/html' ]

		google_cloud:
		  type: service
		  id: monolog_psr_batch_logger

	services:

	  monolog_psr_batch_logger:
		class: Monolog\Handler\PsrHandler
		arguments: [ '@google_cloud_stackdriver_psr_batch_logger' ]

	  google_cloud_stackdriver_psr_batch_logger:
		class: Google\Cloud\Logging\PsrLogger
		factory: [ 'Google\Cloud\Logging\LoggingClient', 'psrBatchLogger' ]
		arguments: [ 'myprojectxxx-logs' ]

**Comment by bshaffer** [comment]
According to [the symfony docs](https://symfony.com/doc/current/logging/handlers.html) for adding a custom handler, this is how it's done. If it's not working, I'd have to debug further, but this looks accurate to me.

**Comment by meredithslota** [comment]
Closing as this apparently WAI based on comment above but if you are still seeing a problem, please open a new issue. Thanks!
