### ISSUE TITLE
Pub/Sub: add schema samples

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/php-docs-samples#1299]
- [ ] create avro schema
- [ ] create proto schema
- [ ] get schema
- [ ] list schemas
- [ ] delete scheam
- [ ] create topic with schema
- [ ] publish avro records
- [ ] publish proto messages
- [ ] subscribe with avro schema
- [ ] subscribe with proto schema

See [Java](https://github.com/googleapis/java-pubsub/pull/509) and [Python](https://github.com/googleapis/python-pubsub/pull/306) examples. 

See published schema [docs](https://cloud.google.com/pubsub/docs/schemas).

**Comment by saranshdhingra** [comment]
I think these are all done as I can see them present in the repo. Closing it, but feel free to open it if something appears missing :)
