### ISSUE TITLE
endpoints: add /auth/info/firebase endpoint

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/php-docs-samples#131]
This one needs CORS headers.

See sample implementation here:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/app.go

and copy the new swagger file:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/swagger.yaml

**Comment by meredithslota** [comment]
@broady Both of those files give me a 404 — have they moved? I'm tempted to close this as `obsolete` but if there's still a need for this ... adding the "triage me" label instead. :)

**Comment by meredithslota** [comment]
Closing as no clear path forward, feel free to reopen if needed!
