### ISSUE TITLE
BetaAnalyticsDataClient Authentication Error: Invalid OAuth scope or ID token audience 

### ISSUE THREAD

**Issue by JCarlosR** [GoogleCloudPlatform/php-docs-samples#1350]
I am trying to use the **Google Analytics Data API** (GA4): https://github.com/googleapis/php-analytics-data#installation

And I get this error message when setting a **credentials json file**:
```
$client = new BetaAnalyticsDataClient([
  'credentials' => $json
]);
            
$response = $client->runReport([
  'property' => $request->input('property_id')
])
```

```
Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}
```

I already tried:
- Specifying a `propertyId` in the array passed to `BetaAnalyticsDataClient`
- Sending the json content vs a path to the json
- Creating a Google Client (https://github.com/googleapis/google-api-php-client) but the `BetaAnalyticsDataClient` doesn't accept it

And I already verified:
- The credentials json file is valid (as it is being used to query the GA Reporting API)
- The Google Analytics Data API is enabled for the project and has available quota
- The Google Analytics Data API is associated to the service account
- The service account is active and associated to the web property (actually the issue happens in the authentication, but just in case)

___

This is the content of the credentials json file:

```
{
  "type": "service_account",
  "project_id": "***",
  "private_key_id": "***",
  "private_key": "-----BEGIN PRIVATE KEY-----\***\n-----END PRIVATE KEY-----\n",
  "client_email": "***@***.iam.gserviceaccount.com",
  "client_id": "***",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/***.iam.gserviceaccount.com",
  "scope": "https://www.googleapis.com/auth/analytics.readonly"
}
```
I only replaced my data with `*`s.
The attribute `scope` was not included in the original file.
I tried with and without this.

___

Any insights migh be appreciated.

Thanks.

**Comment by bshaffer** [comment]
Hello! I cannot duplicate your error. I've tried with the following code, and the oauth token is retrieved as expected:

```php
use Google\Analytics\Data\V1beta\BetaAnalyticsDataClient;

$client = new BetaAnalyticsDataClient([
    'credentials' => json_decode(file_get_contents(getenv('GOOGLE_APPLICATION_CREDENTIALS')), true)
]);

$response = $client->runReport([
    'property' => 'properties/1234'
]);
```

I even added the `scope` parameter in my service account JSON, which is the only key difference between our JSON files, and this still worked as expected. You can try removing the `scope` key but otherwise I am not sure what your issue could be here.

**Comment by jbrown0824** [comment]
I was also getting this exact error. I traced it as far as the jwt not providing a scope.

I finally figured out it's because I already had google/auth 1.9 installed as a dependency from another package in composer.json. When I upgraded `google/auth` to 1.16.0, it started working
