### ISSUE TITLE
You can retrieve the physical path of the file?

### ISSUE THREAD

**Issue by devthiagolino** [GoogleCloudPlatform/php-docs-samples#138]
I need the physical path of the file to edit on my local machine, you can recover the path of the file with PHP?

**Comment by tmatsuo** [comment]
Sorry I don't understand your question. Can you elaborate?

**Comment by devthiagolino** [comment]
Yes.
What I need is the following, `gs://bucket/myfile.ext` because I'm using a library FPDF to write the PDF file and the library needs of the file path.

**Comment by bshaffer** [comment]
Closing because this question is unclear. Please open another issue with further clarification if necessary.
