### ISSUE TITLE
Fix variable case inconsistency in BigTable samples

### ISSUE THREAD

**Issue by saranshdhingra** [GoogleCloudPlatform/php-docs-samples#1385]
In a lot of the BigTable samples, some variables use snake case while some use camel case. Often in the same code block.

Case in point, the sample to [create a cluster](https://cloud.google.com/bigtable/docs/samples/bigtable-create-cluster) uses the variables `$instance_id` and `$cluster_id` but also, `$instanceName` and `$clusterName`.

I could send a PR that changes the snake case variables to camel case for the existing samples.

**Comment by danoscarmike** [comment]
Fixed by #1387
