### ISSUE TITLE
Upgrade all samples to new sample format

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docs-samples#1389]
We have a new samples format that greatly reduces the complexity and overhead of maintaining samples by using reflection to invoke the sample method. We need to upgrade all samples to use this format.

**Background**
We have two existing formats, the `symfony/console` format and the "functionless" format.
1. The `symfony/console`format: This format uses the `symfony/console` component to create an executable command file (e.g. [`vision.php`](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/vision/vision.php)) which executes the samples. This requires the overhead of adding every sample to the command file, and adds a layer of abstraction for the users.
2. The "functionless" format: This format uses [inline PHP](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/bigtable/src/create_cluster.php#L32) to execute the sample. This has the advantage of making the sample files executable, but we lose the wrapping function, which is useful for consistency and documentation.

**The New Format**
The new format uses a method in [`testing/sample_helpers.php`](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/testing/sample_helpers.php#L7) to execute the function automatically from the CLI, and also to print usage instructions based on the PHP doc for the function. All that is required is [these two lines](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/asset/src/export_assets.php#L53) at the bottom of each sample file.

**Samples already upgraded**
 - [x] Asset (#1311)
 - [x] Compute
 - [x] Firestore (#1363, #1381)
 - [x] Pubsub (#1356)
 - [x] IAP (#1378)
 - [x] IOT (#1379)
 - [x] Spanner (#1234)
 - [x] Auth (#1375)
 - [x] Storage (#1384)
 - [x] Bigtable (#1496)
 - [x] DLP (#1615)
 - [x] [TextToSpeech](texttospeech) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1641)
 - [x] [Video](video) (9 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1639)
 - [x] [SecretManager](secretmanager) (15 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1647)
 - [x] [Language](language) (13 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1650)
 - [x] [Speech](speech) (14 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1642)
 - [x] [KMS](kms) (36 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1649)
 - [x] [logging](logging) (4 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1643)
 - [x] [translate](translate) (21 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1719)
 - [x] [BigQuery](bigquery/api) (28 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1720)
 - [x] [error_reporting](error_reporting) (1 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1726)
 - [x] [vision](vision) (4 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1638)
 - [x] [datastore/tutorial](datastore/tutorial) (6 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1648)
 - [x] [monitoring](monitoring) (27 samples) (https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1640)
 - [x] [securitycenter](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1761)
 - [x] [servicedirectory](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1762)

**Samples in progress** 
 - [ ] [endpoints/getting-started](endpoints/getting-started) (1 sample app)

**Samples still using `symfony/console` format**
 - [x] ~~[appengine/flexible/tasks](appengine/flexible/tasks)~~ (not maintained)
 - [x] ~~[appengine/flexible/wordpress](appengine/flexible/wordpress)~~ (not maintained)
 - [x] ~~[appengine/flexible/drupal8](appengine/flexible/drupal8)~~ (not maintained)
 - [x] ~~[appengine/flexible/symfony](appengine/flexible/symfony)~~ (not maintained)
 - [x] ~~[dialogflow](dialogflow) (19 samples)~~ (not maintained)

**Comment by saranshdhingra** [comment]
> All that is required is these two lines at the bottom of each sample file.

This seems a bit _"un-natural"_ for us to do.
 
As a thought, having this functionality in a trait seems more "Object-Oriented" style?
It would also be much easier for the users(and more visible) to remove the trait in their original code.
Something like the following comes to mind:
```php
class ListClusterSample{
  use Google\Cloud\Samples\SampleHelperTrait;
  
  // samples
}

(new ListClusterSample())->executeSample();
```

**Comment by bshaffer** [comment]
@saranshdhingra The primary purpose is to illustrate how to perform whatever function the sample is there to illustrate. Surrounding the sample in an object and including a trait will make the sample itself confusing and take away from this primary purpose.

The direction we have chosen allows the sample to remain entirely unchanged except for two lines at the bottom of the file, which are excluded from the region tags.

**Comment by bshaffer** [comment]
Closing this because all standard samples are upgraded. Will open a new issue for Endpoints
