### ISSUE TITLE
Code coverage not available for PHP 8.0

### ISSUE THREAD

**Issue by saranshdhingra** [GoogleCloudPlatform/php-docs-samples#1430]
Trying to run the bigtable tests using this command:
```
cd bigtable
php PATH_TO_HP_UNIT_FOLDER/phpunit --verbose -c ./phpunit.xml.dist ./test
```

returns this error: `Error:         This version of PHPUnit does not support code coverage on PHP 8`

**Note that this doesn't halt testing.**

I think PHPUnit > `v9.3` supports code coverage for PHP 8. So, simply changing the testing/composer.json line to `"phpunit/phpunit": "^7|^8|^9"` does the trick.

**Comment by bshaffer** [comment]
I haven't tested with PHPUnit 9 yet, and would be interested to see what happens. It may break compatibility with previous versions of PHP (phpunit has been quite aggressive with their upgrades). 

It's worth mentioning that the testing in this repo does not generate any code coverage reports.

**Comment by saranshdhingra** [comment]
Since the error only affects the code coverage, closing the issue.
