### ISSUE TITLE
Cannot access mysql 2nd gen through proxy

### ISSUE THREAD

**Issue by dknesek** [GoogleCloudPlatform/php-docs-samples#145]
Strangely, there was one time that I followed your Wordpress instructions and everything worked fine. That was with my old GCP account.

My client created their own account and I've tried to duplicate the process, but can't login to MySQL through the proxy. (See errors below.)

Started up the proxy.

>Dougs-Mac:secondmarketcapital-website doug$ ../cloud_sql_proxy -dir /tmp/cloudsql -instances=secondmarketcapital-website:us-central1:wp=tcp:3306 -credential_file=secondmarketcapital-website-169172622c01.json &
[1] 27461
>Dougs-Mac:secondmarketcapital-website doug$ 2016/08/14 22:36:18 Listening on 127.0.0.1:3306 for secondmarketcapital-website:us-central1:wp
2016/08/14 22:36:18 Ready for new connections

Tried to connect.

>Dougs-Mac:secondmarketcapital-website doug$ /usr/local/mysql/bin/mysql -h 127.0.0.1 -u root -p
Enter password: 
2016/08/14 22:59:19 New connection for "secondmarketcapital-website:us-central1:wp"
2016/08/14 22:59:19 couldn't connect to "secondmarketcapital-website:us-central1:wp": ensure that the account has access to "secondmarketcapital-website:us-central1:wp" (and make sure there's no typo in that name). Error during createEphemeral for secondmarketcapital-website:us-central1:wp: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

Something makes me think I've not don't the service account correctly. Under "select a role" I picked "Project/Service Account Actor", but I'm not sure that was correct.

![image](https://cloud.githubusercontent.com/assets/185153/17655482/6d581d86-6274-11e6-9e90-fc7db2095ae3.png)

**Comment by tmatsuo** [comment]
Yeah, now the service account needs to be an editor of the project.
