### ISSUE TITLE
error when using google speech

### ISSUE THREAD

**Issue by showf68** [GoogleCloudPlatform/php-docs-samples#1452]
16384: The class Google\Cloud\Speech\Result is no longer supported in /usr/share/php/vendor/google/cloud-speech/src/Result.php on line 59

16384: The class Google\Cloud\Speech\Connection\Rest is no longer supported in /usr/share/php/vendor/google/cloud-speech/src/Connection/Rest.php on line 58

my code:
use Google\Cloud\Speech\SpeechClient;
    $speech = new SpeechClient(['languageCode' => $language]);
    $results = $speech->recognize(fopen($filename, 'r'), ['encoding' => 'LINEAR16', 'sampleRateHertz' => 8000]);

**Comment by bshaffer** [comment]
Hello! You are receiving warnings from the `@deprecated` PHP annotation.

The class `Google\Cloud\Speech\SpeechClient` has been deprecated. Instead, use the class `Google\Cloud\Speech\V1\SpeechClient`. The methods are different as well so please see the [Speech samples](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech) for help. Here's a few to get your started:
 - [Speech Async Recognize](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech/src/transcribe_async.php#L63)
 - [Speech Sync Recognize](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech/src/transcribe_sync.php#L63)
