### ISSUE TITLE
Update cs fixer rules

### ISSUE THREAD

**Issue by saranshdhingra** [GoogleCloudPlatform/php-docs-samples#1465]
Add the cs fixer rules to add the following:

- [x] Change double quotes to single quotes when no escape characters or variables are used within the string.
- [x] Single space after cast, ex: `(int)$var` to become `(int) $var`
- [ ] Implicit else: If an `else` block contains only a `return` or `throw` statement, then it should be executed implicitly.
- [x] Prevent rogue empty lines.
- [ ] Soft/hard limits on comments
- [x] Space around the `arrow` in array declarations. 
- [ ] Variable naming conventions to use camel case - i.e. `$pageNum `instead of `$page_num`
- [ ] Function naming conventions (underscore to divide words) - to be confirmed if isn't already working as expected
- [ ] Proper indentation inside functions, loops etc.

**Comment by rsamborski** [comment]
* Variable naming conventions to use camel case - i.e. $pageNum instead of $page_num
* Function naming conventions (underscore to divide words) - to be confirmed if isn't already working as expected
* Proper indentation inside functions, loops etc.

**Comment by saranshdhingra** [comment]
Closing this as we are discussing to unify efforts across multiple repos.
