### ISSUE TITLE
Use `runtime: php` if possible

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#148]
Some directories still have `runtime: custom`, but we should use `runtime: php` if possible.

- [x] appengine/flexible/symfony
- [x] appengine/flexible/drupal8

**Comment by bshaffer** [comment]
see https://github.com/GoogleCloudPlatform/php-docs-samples/pull/190

**Comment by tmatsuo** [comment]
Yay!
