### ISSUE TITLE
php-docs-samples functions http_form_data index.php 

### ISSUE THREAD

**Issue by oliver7733** [GoogleCloudPlatform/php-docs-samples#1531]
is the sample code workable on GCF?

**Comment by ace-n** [comment]
Hi @oliver7733 and thanks for the issue.

I was able to get the function itself working without any errors.

Since this issue is fairly old, I'm going to go ahead and close it.

If you're still having problems, **please reopen this one** and let us know what errors you're running into.

Thanks! 😃
