### ISSUE TITLE
App engine standard SQL Server

### ISSUE THREAD

**Issue by david-muenzer** [GoogleCloudPlatform/php-docs-samples#1605]
Hello,

I read in here https://cloud.google.com/sql/docs/sqlserver/connect-app-engine-standard that you can connect to sql server from app engine standard env. The code example refers to a github sample https://github.com/GoogleCloudPlatform/php-docs-samples/tree/f3907481ba3380c7ef83c41e4e68189124f3f5c2/cloud_sql/sqlserver/pdo that states sqlsrv is needed to connect to SQL Server through app engine which is only possible through a costum runtime (which also is what my testing resulted in). The code example given in https://cloud.google.com/sql/docs/sqlserver/connect-app-engine-standard underlies this since it uses the sqlsrv in the connection:

```php
// $username = 'your_db_user';
// $password = 'yoursupersecretpassword';
// $dbName = 'your_db_name';
// $dbHost = "127.0.0.1";

// Connect using TCP
$dsn = sprintf('sqlsrv:server=%s;Database=%s', $dbHost, $dbName);

// Connect to the database
$conn = new PDO($dsn, $username, $password, $connConfig);
```

My conclusion is now that it is not possible to connect to the sql server through the app engine standard env...or is there a way?

If you cant connect to SQL Server through app engine stanard env maybe update https://cloud.google.com/sql/docs/sqlserver/connect-app-engine-standard that no other people get confused.

best regards,
David

**Comment by bshaffer** [comment]
Hello @david-muenzer ! I have good news!

It isn't that MSSQL isn't supported by App Engine Standard, it's that the `sqlsrv` extension isn't available. It's possible to [install custom extensions](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/standard/extensions), so you can activate `sqlsrv.so` that way by following these steps:

1. Download SQL Server Extension code and put it in your app engine application:
```bash
# downloads sqlsrv-5.10.1.tgz
wget https://pecl.php.net/get/sqlsrv-5.10.1.tgz
tar xvf sqlsrv-5.10.1.tgz 
mv sqlsrv-5.10.1.tgz sqlsrv
```

2. Put the commands to compile the extension in your `composer.json`:

```json
{
    "scripts": {
        "post-autoload-dump": [
            "cd sqlsrv && phpize --clean && phpize && ./configure && make",
            "cp sqlsrv/modules/sqlsrv.so vendor/"
        ]
    }
}
```

3. Activate the extension in your `php.ini`:
```ini
# php.ini
extension=/workspace/vendor/sqlsrv.so
```

4. Add an `app.yaml` and `index.php` so you can see that the extension was configured correctly:
```yaml
# app.yaml
runtime: php81
```
```php
<?php

phpinfo()
```

5. Now just run `gcloud app deploy`.  I haven't tested this more than just making sure the extension is activated though, but it should work.

**Comment by david-muenzer** [comment]
Thank you very much, helped a lot ! :-)
