### ISSUE TITLE
Reference to Blog Links are broken

### ISSUE THREAD

**Issue by ZackTherrien** [GoogleCloudPlatform/php-docs-samples#1619]
I'm not sure about other examples, however for this specific sample, the link in the README is broken and redirects to another blog/article. 
Can we update to the new article URL?
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/standard/laravel-framework

**Comment by bshaffer** [comment]
This tutorial is no longer available because it had issues and we did not have the resources to fix them

I've created [this PR](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1651) to remove the URL and mark the tutorial as deprecated.
