### ISSUE TITLE
Data API v1 quota user parameter in PHP lib

### ISSUE THREAD

**Issue by Eldair** [GoogleCloudPlatform/php-docs-samples#1632]
How do I add quota user parameter in PHP lib of Data API v1 and in Admin API?

**Comment by bshaffer** [comment]
I believe you're referring to the Quota Project? I am not sure about a Quota User, but if. you'd like to set the quota project you can do so in the Service Client like this:

```php
$credentialsConfig = [
    'quotaProject' => 'your-project-id-for-quota',
];
$client = new AnalyticsAdminClient([
    'credentialsConfig' => $credentialsConfig,
]);
// make calls with your client using the quota project specified.
```

**Comment by bshaffer** [comment]
That is determined by the account which authorizes the request, there is no way to set it as a parameter.

**Comment by Eldair** [comment]
So it is automatically applied now, it is a manual thing in the reporting API so just checking?

**Comment by dwsupplee** [comment]
There is a quotaUser top level parameter that appears it can be set as a query parameter: https://analyticsdata.googleapis.com/$discovery/rest?version=v1beta

<img width="377" alt="Screen Shot 2022-06-14 at 2 14 50 PM" src="https://user-images.githubusercontent.com/2079879/173690247-ffc660cf-22a7-4cf0-97f9-2cb99791c776.png">

Is this something we should support along side quota project?

**Comment by Eldair** [comment]
That is exactly what I was looking for and it would be great to have it usable if it is not automatic based on auth user.

**Comment by Eldair** [comment]
@dwsupplee any news on whether this will get implemented?
