### ISSUE TITLE
refactor(storage): Dual-Region Sample for Updated API

### ISSUE THREAD

**Issue by danielbankhead** [GoogleCloudPlatform/php-docs-samples#1645]
[Internal]
- For details and coordination: [go/gcs-dpe-dual-region-milestones-api-refactor](http://go/gcs-dpe-dual-region-milestones-api-refactor)
- Implementation Example: https://github.com/googleapis/nodejs-storage/pull/1977

**Comment by vishwarajanand** [comment]
Similar to this one: https://github.com/googleapis/google-cloud-php/issues/5313

**Comment by vishwarajanand** [comment]
Samples are already present, we just need to update them.
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/073a6cc62373256d5f5e3abbf158289d8af21af2/storage/src/create_bucket_dual_region.php#L36-L48
