### ISSUE TITLE
memcache php  instrucitons should read memcached

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/php-docs-samples#168]
please replace /memcache/   with [/memcached/](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/memcache/app.php#L99)  in README.md

> Store and retrieve values from the cache.
``
$ curl http://{YOUR_PROJECT_ID}.appspot.com/memcached/a
$ curl http://{YOUR_PROJECT_ID}.appspot.com/memcached/a -T hello.txt
$ curl http://{YOUR_PROJECT_ID}.appspot.com/memcached/a
```

**Comment by bshaffer** [comment]
Both `/memcache` and `/memcached` are valid endpoints in the sample

**Comment by salrashid123** [comment]
i think its only /memcached 

https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/memcache/app.php#L99

eg
```
$ curl -I https://<appid>.appspot.com/memcache/somekey

HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Vary: Accept-Encoding
Cache-Control: no-cache
Via: iwhx63:26103
X-Cloud-Trace-Context: 4b3b5324172a694b8496128f4a6c328d;o=1
Date: Sat, 24 Sep 2016 01:30:48 GMT
Server: Google Frontend
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34,33,32"
Transfer-Encoding: chunked
```
```
$ curl -I https://appid.appspot.com/memcached/somekey

HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Vary: Accept-Encoding
Cache-Control: no-cache
Via: iwfr126:26254
X-Cloud-Trace-Context: 95ab69794f29f9ece5ac7bc4adde948e;o=1
Date: Sat, 24 Sep 2016 01:30:51 GMT
Server: Google Frontend
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34,33,32"
Transfer-Encoding: chunked
```

**Comment by bshaffer** [comment]
You're right, I was looking at the [AppEngine Standard sample](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/memcache/app.php#L53)
