### ISSUE TITLE
Speech: longRunningRecognize pollUntilCOmplete has deprecated php codes

### ISSUE THREAD

**Issue by chapman-cc** [GoogleCloudPlatform/php-docs-samples#1688]
Running the longRunningRecognize code :
```
$op = $speechCLient->longRunningRecognize($config, $audio);
$op->pollUntilComplete(); 
...others 
```

would return the following warning/error
```
PHP Deprecated:  Implicit conversion from float 1687.5 to int loses precision in /path/to/php/project/root/vendor/google/gax/src/PollingTrait.php on line 93
```

**Comment by mattcarrolldev** [comment]
@ChapmanCheng Can you provide more information on your issue? for instance what are the values of `$config` and `$audio` and `$speechClient`? What version of the speech library and you using? What version of PHP are you using? what platform (linux, macOS, Windows, etc.) are you using?
