### ISSUE TITLE
Bigquery: Update samples format.

### ISSUE THREAD

**Issue by saranshdhingra** [GoogleCloudPlatform/php-docs-samples#1704]
Update the samples to use the new format like in other products.
[Reference](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/bigtable/src/create_table.php)

**Comment by vishwarajanand** [comment]
May refer to https://github.com/ajupazhamayil/function_param_example_comment_remover/

**Comment by yash30201** [comment]
Fixed #1720
