### ISSUE TITLE
feat: upgrade or remove Endpoints getting started sample

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docs-samples#1763]
The [endpoints/getting-started](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/endpoints/getting-started) sample app is outdated, and needs to be either upgraded to the new format or removed. 

I have started upgrading the sample in https://github.com/GoogleCloudPlatform/php-docs-samples/commit/f36e623812240582b26ebbcab6593e3f3a58930b, but I'm not sure this works, or is even still a part of our cloud site samples.

**Comment by vishwarajanand** [comment]
Thanks for taking this up @bshaffer. 
I checked it, there are only 3 tags in `/endpoints` swagger, esp and configuration. All of them are not tracked with a product but are used on cloud site.

**Comment by vishwarajanand** [comment]
I will check whether the endpoints samples are showing up in dashboards. If they do, goal is to remove them.

**Comment by bshaffer** [comment]
> but are used on cloud site.

That's good to know, and says to me we should keep them / update them if possible!

**Comment by vishwarajanand** [comment]
Fixed by #1862
