### ISSUE TITLE
Typos in the Analytics Examples

### ISSUE THREAD

**Issue by julesgilson** [GoogleCloudPlatform/php-docs-samples#1772]
In the Analytics sample scripts that include filters, the filter array key is wrong. The run_report method is expecting camelcase and snakecase is used in the examples.

Example script:
[https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/analyticsdata/src/run_report_with_dimension_filter.php](url)

```
'dimension_filter' => new FilterExpression([
  'filter' => new Filter([
    'field_name' => 'eventName',
    'string_filter' => new StringFilter([
      'value' => 'first_open'
     ]),
  ]),
]),
```

Should be:

```
'dimensionFilter' => new FilterExpression([
  'filter' => new Filter([
    'field_name' => 'eventName',
    'string_filter' => new StringFilter([
      'value' => 'first_open'
     ]),
  ]),
]),
```

Same for `metricFilter`

**Comment by bshaffer** [comment]
Thank you for submitting this issue. I've added a fix for this in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1788
