### ISSUE TITLE
Implicit conversion from float 3988292384 to int loses precision Error in PHP 8.1 

### ISSUE THREAD

**Issue by parwinderdev** [GoogleCloudPlatform/php-docs-samples#1820]
Hi Team,
we are using "google/cloud-storage": "^1.30"
We are uploading media file on firebase storage. With the help of under given code. 

`$object = $bucket->upload(file_get_contents($file), [
					'name' => $foldername . '/' . $filename,
					'metadata' => ['contentType' => $filetype]
				]);
				$upload_info = $object->info();` 
				
The upper code working fine for PHP 7 version but now we have upgrade to PHP 8.1. After the version upgrade we are facing error while upload files.

**Message**:  Implicit conversion from float 3988292384 to int loses precision  
**Filename**: src/Builtin.php
**Line Number**: 44
 
**Please check the screen-shot as well** 

![image](https://user-images.githubusercontent.com/98552395/234525271-21cbb690-7108-4eb2-82f6-87509f7209d7.png)

Could you please let us know how we can fix this ?

Looking forward.

**Comment by vishwarajanand** [comment]
Dup of https://github.com/googleapis/google-cloud-php/issues/6115, closing the issue here.
