### ISSUE TITLE
Error in \appengine\flexible\wordpress

### ISSUE THREAD

**Issue by sitlarussell** [GoogleCloudPlatform/php-docs-samples#1891]
Followed the steps described in the [readme](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/main/appengine/flexible/wordpress) - I'm running php 8.2 by running the following:

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.2"
  document_root: ./wordpress

When I first access the page the site it redirects to /wp-admin/install.php but is stuck in a 302 redirect loop. ERR_TOO_MANY_REDIRECTS

I assume this is an issue with nginxserver.conf

**Comment by bshaffer** [comment]
Unfortunately App Engine Flex samples are no longer maintained. If you do find a solution please post it here!
