### ISSUE TITLE
Create samples for storageinsights

### ISSUE THREAD

**Issue by JesseLovelace** [GoogleCloudPlatform/php-docs-samples#1899]
Please create the following samples for the Storage Insights API, using [this](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8460) as a reference 

storageinsights_create_inventory_report_config
storageinsights_delete_inventory_report_config
storageinsights_edit_inventory_report_config
storageinsights_get_inventory_report_names
storageinsights_list_inventory_report_configs

**Comment by saranshdhingra** [comment]
Hey @yash30201, please have a look at this.
