### ISSUE TITLE
Add e2e test for endpoint sample

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#193]

**Comment by tmatsuo** [comment]
Some tricky parts;

- you need to use gcloud beta app deploy, maybe we should tweak our deploytrait to make the command configurable
- you need to create an API key like curl -vv -d '{"message":"foo"}' -H 'Content-Type: application/json' "${ENDPOINTS_HOST}/echo?key=${ENDPOINTS_KEY}"
- ideally you should test it without the API key and check if it's correctly 404

**Comment by bshaffer** [comment]
This was added [here](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/endpoints/getting-started/test/DeployTest.php), but we now need e2e for `GCE` and `GKE` as well.

**Comment by jeffmendoza** [comment]
Awesome, I'm working on a doc for GKE testing.

**Comment by meredithslota** [comment]
Closing due to capacity — will revisit if needed later on.
