### ISSUE TITLE
run/laravel tests not configured correctly

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/php-docs-samples#1932]
Identified in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1931

https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/run/laravel/phpunit.xml#L9 is referencing a file that doesn't exist.

**Comment by glasnt** [comment]
Kokoro expects a `/test/` folder. (in some cases, https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/testing/run_test_suite.sh#L165. Latest error says "
find: 'run/laravel/test/': No such file or directory" which I think maps to the `find` command in https://source.cloud.google.com/results/invocations/9faf8443-ec1a-4363-ab31-9f52a139cca6/targets/cloud-devrel%2Fphp-docs-samples%2Fpresubmit%2Fphp80/log)

Laravel hardcodes a `/tests/` folder https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Console/TestMakeCommand.php#L84

**Comment by bshaffer** [comment]
@glasnt this should be fixed in #1991 - I updated the script to hide the "No such file or directory" error output, and to check in both `test` and `tests` dirs.
