### ISSUE TITLE
Are Firestore aggregation queries supported? (count, sum etc)

### ISSUE THREAD

**Issue by giorgio79** [GoogleCloudPlatform/php-docs-samples#1955]
Are aggregation queries supported? :) ChatGPT said this php library does not :P 

https://firebase.google.com/docs/firestore/query-data/aggregation-queries#dart

**Comment by shivgautam** [comment]
It is available and was released on Dec 1. https://github.com/googleapis/google-cloud-php/pull/6786

**Comment by giorgio79** [comment]
Much appreciated! Could we get some php samples pls here? https://firebase.google.com/docs/firestore/query-data/aggregation-queries

**Comment by shivgautam** [comment]
Yes. We are discussing it internally. Will be working on it. Can't provide an ETA at the moment though.

**Comment by giorgio79** [comment]
Found a sample in the comment here https://github.com/googleapis/google-cloud-php/blob/main/Firestore/src/AggregateQuery.php but I am getting 0 in my own tests. Will wait for sg official on that page :P

` * Example:
 * ```
 * use Google\Cloud\Firestore\FirestoreClient;
 *
 * $firestore = new FirestoreClient();
 *
 * $collection = $firestore->collection('users');
 * $query = $collection->where('age', '>', 18)->count();`

**Comment by shivgautam** [comment]
Here are a few examples to get you started in the meantime: 
https://github.com/googleapis/google-cloud-php/blob/main/Firestore/src/Aggregate.php#L66-L116
