### ISSUE TITLE
Question on Instances

### ISSUE THREAD

**Issue by jgacuca567** [GoogleCloudPlatform/php-docs-samples#196]
@tmatsuo

If I have one instance created and want to create multiple wordpress sites, do I have to create each instance for each project?

Can I run more than one database on a single instance?

What is the benefit and disadvantage of either?

**Comment by bshaffer** [comment]
Hi @jgacuca567!

The database used with the App Engine Wordpress deployment script is CloudSQL, so MySQL does not run on the instances. Instead, they run through your managed CloudSQL instance, so you won't have to worry about scaling. As far as the instances go, once you deploy a single instance, App Engine automatically scales to multiple instances as needed depending on your traffic.

I'm closing this issue for now, but let me know if you have any more questions!

**Comment by tmatsuo** [comment]
Hi @jgacuca567 Sorry for the late reply from me.

Also there is a multi site plugin for WordPress, I wrote a small blog post about that at:
https://wp.gaeflex.ninja/2016/03/25/using-wordpress-multisite/

Hope it helps!
