### ISSUE TITLE
Memcache not found

### ISSUE THREAD

**Issue by slajar** [GoogleCloudPlatform/php-docs-samples#223]
After installing and while running vendor/bin/wp server I am getting this error on MacOSX in standard mode:

Class 'Memcache' not found in my-wordpress-project/wordpress/wp-content/object-cache.php on line 425

The file object-cache.php resides in multiple locations. That looks a bit weird.

**Comment by bshaffer** [comment]
It looks like you need to install or enable the memcache PHP extension. This is easiest via homebrew:

```sh
brew install php56-memcache
```

Where `php56` assumes you are running version PHP 5.6.
