### ISSUE TITLE
Cloud SQL flex app should have beta_settings and MYSQL env vars in app.yaml

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#234]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/cloudsql/app.yaml

**Comment by bshaffer** [comment]
This example is for first generation Cloud SQL. We'll also need to upgrade the README and tests for Second Generation.

**Comment by bshaffer** [comment]
Added in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/218
