### ISSUE TITLE
How to use gprc live streaming conversation 

### ISSUE THREAD

**Issue by webmarts** [GoogleCloudPlatform/php-docs-samples#250]
His
I am able to convert audio file to text, can any one help me how to use gprc for live streaming voice conversation

**Comment by webmarts** [comment]
Hi
I am able to convert audio file to text, can any one help me how to use gprc for live streaming voice conversation

**Comment by bshaffer** [comment]
hi @webmarts! We currently do not support streaming for the Speech API, but stay tuned.

**Comment by bshaffer** [comment]
You can check out examples of this in [NodeJS](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/speech/recognize.js#L104) and [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/grpc/transcribe_streaming.py#L214)

**Comment by bshaffer** [comment]
Added in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/342

see https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/speech/api: 

```
$ cd speech/api
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
$ php speech.php test/data/audio32KHz.raw --stream --encoding LINEAR16 --sample-rate 32000 
```
