### ISSUE TITLE
Google App Engine PHP Wordpress Common Errors

### ISSUE THREAD

**Issue by jgacuca567** [GoogleCloudPlatform/php-docs-samples#261]
Below are the common errors I keep experiencing when trying to setup Wordpress on GoogleCloud. 

# Version 

- State which platform should work best and which PHP Version is best either PHP5 or PHP7. 
- State which  memcached plugin is required, list the url to download the memcached plugin. \
- State whether we should use flexible or standard version. 

## Changing the port
[Port Changing](https://cloud.google.com/appengine/docs/php/tools/using-local-server)
It is very difficult to change from localhost:8080 to localhost:8081, any ideas showing how to do that would be greatful especially when running multiple, wordpress sites. 

## PHP Executable Path
[How to change the path](http://stackoverflow.com/questions/20618871/google-app-engine-php-executable-path-not-found)
When installation is complete, Wordpress asks, to change the PHP Executable path, any ideas showing how to do this would be greatful. 

## Wordpress Continous Reload
After setting up the site, the site keeps reloading and no error shows, whats going on. 
Nothing is showing up in the error logs pages. 

## Vendor Folder not Created
When setting up, the vendor folder is not created and the site can't run without the vendor folder. 

### Deprecate the following Github 
@tmatsuo @bshaffer
https://github.com/GoogleCloudPlatform/appengine-php-wordpress-starter-project, from your webpage, use that one as the official one, since there are now multiple ones. This will avoid the confusion.

**Comment by tmatsuo** [comment]
@jgacuca567 Thanks for the feedback!

We're working on to provide better documentation on how to run WordPress on GCP. We'll definitely improve the issues you raised here.

Thanks again!

**Comment by jgacuca567** [comment]
@tmatsuo Let me know how I can be of assistance.

**Comment by bshaffer** [comment]
@jgacuca567 Thank you for this feedback! This is very helpful. Did you try using the starter project, and if so what was your experience?

**Comment by jgacuca567** [comment]
@bshaffer 
So far so good, scales rapidly, but if the errors keep getting fixed then it shall be good to go.

**Comment by bshaffer** [comment]
@jgacuca567 by starter project I am referring to [this repository](https://github.com/GoogleCloudPlatform/appengine-php-wordpress-starter-project). I assume the comments you've left on here refer to [this one](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/wordpress).

**Comment by jgacuca567** [comment]
@bshaffer The one I have been using is the one from php-docs-samples, haven't been using the app-engine one since its the old version, have been using @tmatsuo's version.

**Comment by jgacuca567** [comment]
@bshaffer @tmatsuo have you tried to test using MAMP PRO as well and is OpenSSL a requirement?
