### ISSUE TITLE
App Engine / Wordpress

### ISSUE THREAD

**Issue by eugeneross** [GoogleCloudPlatform/php-docs-samples#285]
Upon a successful app build and deployment to App Engine, once I decided to promote the version with Wordpress installed (omitted the `--promote --stop-previous-version` flags) I am receiving a 403 error at my project url, both the `.appspot.com` domain and custom domain. I tried multiple urls such as:

- /wp
- /wordpress
- /app/wordpress
- /wp-login.php
- /wp-config.php

thinking something functioning may be at one of those options. 

I had checked the logs for anything obscene, but could not see anything causing any issues.

I would really appreciate any help to figure my problem out. Let me know if there's any info I can provide that would help.

**Comment by tmatsuo** [comment]
@eugeneross Thanks for the report. Is it possible for you to send some information and files over to me (tmatsuo@google.com)?

```
cloud project id
custom domain name
app.yaml
nginx-app.conf
```

Is it also possible to invite me as a viewer of the cloud project so that it'll be easier for me to check the logs?

**Comment by eugeneross** [comment]
@tmatsuo Just sent it along! I will invite you as well. Thank you.

**Comment by daron4ever** [comment]
I'am new here and please help me to apply WordPress.
---------------
The media file was saved localhost:8080/_ah/gcs/app_default_bucket/filename
It worked during the development time.
But when I continuously developed next day, the file in the Media library has been missing.
---------------
So, I have installed the client library and i don't know how to run with my wordpress project.
The help would be appreciated.

**Comment by jgacuca567** [comment]
@daron4ever please create a new issue separately then cc @tmatsuo, explain how you got to the localhost part
