### ISSUE TITLE
[Wordpress] CloudSQL access not possible

### ISSUE THREAD

**Issue by derjust** [GoogleCloudPlatform/php-docs-samples#288]
Hi everyone!

I just try to install a bare WordPress and followed the `README.md` steps.
The CloudSQL instance is running and I can access it locally via the `cloudsql-proxy`.

After fixing the `app.yaml` to use the flexible AppEngine setting to

```
env: flex
```

and `wp-config.php`

```
    /** Production environment */                                                                                                
    define('DB_HOST', ':/cloudsql/$PROJECT_ID:us-east1:$DBNAME');                                                         
    /** The name of the database for WordPress */                                                                                
    define('DB_NAME', '$DBNAME');                                                                                              
    /** MySQL database username */                                                                                               
    define('DB_USER', '$DBUSERNAME');                                                                                              
    /** MySQL database password */                                                                                               
    //define('DB_PASSWORD', '$DBPASSWORD'); 
```

deployment works but opening any page in Wordpress ends (after a long time) in the following error:

```
Warning: mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wordpress/wp-includes/wp-db.php on line 1538 Warning: mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/wordpress/wp-includes/wp-db.php on line 1538 Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /app/wordpress/wp-includes/wp-db.php on line 1568 Notice: mysql_connect(): SQL safe mode in effect - ignoring host/user/password information in /app/wordpress/wp-includes/wp-db.php on line 1568 Warning: mysql_connect(): No such file or directory in /app/wordpress/wp-includes/wp-db.php on line 1568

Error establishing a database connection
```
Interestingly, using `mysql-client` on the command-line to connect via the socket works.

```
mysql -S /cloudsql/$PROJECTID\:us-east1\:$DBNAME -u $DBUSER -p$DBPASSWORD
```

**Comment by bshaffer** [comment]
Hello @derjust !

Have you updated `app.yaml` to include the cloudsql beta settings?

```yaml
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "CONNECTION_NAME"
```

Where `CONNECTION_NAME` should follow the format `PROJECT_ID:ZONE:DB_NAME`

**Comment by derjust** [comment]
Yes. It exists (it was auto-generated by the setup script).
I can even ssh into the instance and `docker exec` into the app container.
Inside (after installing `mysql-client`) i can use `mysql -S /cloudsql/CONNECTION_NAME` to use the database.

**Comment by bshaffer** [comment]
Check the arguments being passed to `mysqli_real_connect` and verify they match the arguments you are passing on the CLI.

**Comment by derjust** [comment]
Will doublecheck.  Due to multiple documentations stating different versions:
Is `:/cloudsql/$PROJECT_ID:us-east1:$DBNAME` the 'correct' connection string? (some other blogs/tutorials/documentations sprinkle in `socket:/`, `localhost:/` and other pieces)

**Comment by bshaffer** [comment]
Good question. your DSN should look like this:

```
mysql:host=IP_ADDRESS;port=3306;dbname=YOUR_DB_NAME;unix_socket=/cloudsql/CONNECTION_NAME
```

**Comment by daron4ever** [comment]
Hi @derjust ,
Have you solved the issue?
I got the same issue.

**Comment by derjust** [comment]
I ended up with a Standard environment and a 1st Generation CloudSQL - that seem to work.
But my connection string is different. As `gcloud sql instances describe INSTANCE` reports a connection string without a region. So I use it.

**Comment by truptipatel1** [comment]
I have the same problem. I am trying to deploy wordpress into a flex app engine env. Now when I browse the WP page at https://[YOUR_PROJECT_ID].appspot.com 

I get to the admin WP page which states:

Warning: mysqli_real_connect(): (HY000/2002): Connection refused in /app/wordpress/wp-includes/wp-db.php on line 1538 Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /app/wordpress/wp-includes/wp-db.php on line 1568 Notice: mysql_connect(): SQL safe mode in effect - ignoring host/user/password information in /app/wordpress/wp-includes/wp-db.php on line 1568 Warning: mysql_connect(): No such file or directory in /app/wordpress/wp-includes/wp-db.php on line 1568
Error establishing a database connection
This either means that the username and password information in your wp-config.php file is incorrect or we can’t contact the database server at 127.0.0.1. This could mean your host’s database server is down.

Are you sure you have the correct username and password?
Are you sure that you have typed the correct hostname?
Are you sure that the database server is running?
If you’re unsure what these terms mean you should probably contact your host.
