### ISSUE TITLE
Set Content-Type when upload a file

### ISSUE THREAD

**Issue by mavillar** [GoogleCloudPlatform/php-docs-samples#308]
I successfully upload a file to my bucket in GCStorage.

The question is that I do not see how can I set the max-age parameter in the metadata using the PHP API.

Here is the code I use:

```
$file = fopen($_SERVER['DOCUMENT_ROOT']."/uploads/example_50.jpg", 'r');
$bucket = $storage->bucket("my_bucket");
$object = $bucket->upload($file, [
          'name' => "example_50.jpg"
       ]);
$object = $bucket->object("example_50.jpg");
$object->update(['acl' => []], ['predefinedAcl' => 'PUBLICREAD', 'max-age' => 36000]);
```
As you can see, I have tried it but no success.

Any idea?

**Comment by tmatsuo** [comment]
I think it's more appropriate to file this on [google-cloud-php](https://github.com/GoogleCloudPlatform/google-cloud-php) repo. Can you open an issue there?
