### ISSUE TITLE
appwordpress': No such file or directory

### ISSUE THREAD

**Issue by jacksonlima91** [GoogleCloudPlatform/php-docs-samples#311]
Hi, when i execute gcloud app deploy, i got error
chown: cannot access 'appwordpress': No such file or directory

**Comment by jgacuca567** [comment]
@jacksonlima91 Please post how you got to that step.

**Comment by jacksonlima91** [comment]
I simply navigate to the folder of my wordpress project and type gcloud app deploy. It starts the process normally, but then fails with the attached error.
![errorgaewordpress](https://cloud.githubusercontent.com/assets/22433930/22403388/a019e536-e5fc-11e6-9fe3-96de44f09646.JPG)

**Comment by tmatsuo** [comment]
@jacksonlima91 
This is a known bug in older gcloud sdk. Can you upgrade gcloud sdk by the following command and retry?

```
gcloud components update
```

**Comment by jacksonlima91** [comment]
Just update the cloud SDK or will I have to redo the project?

**Comment by tmatsuo** [comment]
@jacksonlima91 Just update the cloud SDK
