### ISSUE TITLE
ImageMagick module not available with this PHP installation

### ISSUE THREAD

**Issue by mgallegos** [GoogleCloudPlatform/php-docs-samples#313]
If there any way to enable modules on appengine flexible.

I'm currently working with a laravel application.

**Comment by bshaffer** [comment]
@mgallegos Yes, you can! Check out [this doc](https://cloud.google.com/appengine/docs/php/runtime#dynamically_loadable_extensions) for a list of dynamically loadable extensions and how to enable them. Also, we have an example of [Laravel on App Engine Flexible](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/laravel)).

**Comment by mgallegos** [comment]
I'm still getting the same error, this is how my php.ini looks like:

```
; we should tighten up these restrictions eventually
suhosin.executor.func.blacklist =
disable_functions =

extension = "curl.so"
extension = "imagick.so"
extension = "fileinfo.so"
```
P.D: Thanks, I'm already using the example Laravel on App Engine Flexible.

**Comment by tmatsuo** [comment]
@mgallegos I think the problem is our docker image doesn't provide imagick extension.

For now, you need to do it by yourself with the custom Dockerfile.

**Comment by mgallegos** [comment]
Thanks for your answer @tmatsuo, I'm going to try to work something out for now.

**Comment by chingor13** [comment]
Enabling imagick via your php.ini should now work.

**Comment by bshaffer** [comment]
Yes, this should be fixed as of https://github.com/GoogleCloudPlatform/php-docker/pull/207. Add the following to the root of your project:

```
# php.ini
extension=imagick.so
```
