### ISSUE TITLE
How to change the default PHP version 7.1

### ISSUE THREAD

**Issue by mgallegos** [GoogleCloudPlatform/php-docs-samples#316]
Is it possible to specify the default php version for my application?

It recently [changed to 7.1 in php-docker](https://github.com/GoogleCloudPlatform/php-docker/commit/5baee599e3591988948698dd9f99255d0b4fccfb) and I getting some incompatibilities in my application.

**Comment by tmatsuo** [comment]
@mgallegos Sorry about that! Please pin php version by:

```
composer require php "~5.6.1"
```
or something like that

**Comment by mgallegos** [comment]
Thanks @tmatsuo for your quick reply.

**Comment by tmatsuo** [comment]
@mgallegos No problem! Did it work for you?

**Comment by mgallegos** [comment]
It didn't, I got the following message:

> Your requirements could not be resolved to an installable set of packages.
Problem 1
    - This package requires php ~5.5.1 but your PHP version (7.1.1) does not satisfy that requirement.

**Comment by tmatsuo** [comment]
What does your composer.json look like?

**Comment by tmatsuo** [comment]
@mgallegos Oh I understand the situation.

The runtime only supports PHP 7.1.x, 7.0.x, and 5.6.x. Can you pin to 5.6.x?

**Comment by mgallegos** [comment]
You were right, it works.

Thanks!
