### ISSUE TITLE
accessing images via https

### ISSUE THREAD

**Issue by meera** [GoogleCloudPlatform/php-docs-samples#319]
I was able to deploy wordpress to google cloud as per instructions. However the images are not being displayed correctly. The site is accessed using https url
https://<myapp>.appspot.com

and the images are getting embedded as http.

I am using wordpress Media Library to upload images. I see that images are being stored in default Bucket. 

Mixed Content: The page at 'https://<myapp>.appspot.com/' was loaded over HTTPS, but requested an insecure image 'http://lh3.googleusercontent.com/CjjwGRVdC5yKpej1C7UhxUNuldysfftsljMvYmr8DXPo9TN0aJO-6-bTId7OW0p2KIH-Q_P6luXvkV6JlyWk6XINAHd8vw=s0'. This request has been blocked; the content must be served over HTTPS.

**Comment by tmatsuo** [comment]
@meera 
I think you're using this plugin:
https://wordpress.org/plugins/google-app-engine/

The plugin has a configuration option for using HTTPS for images. Please turn it on and upload the image again.
