### ISSUE TITLE
Sending E-Mail for ContactForm

### ISSUE THREAD

**Issue by meera** [GoogleCloudPlatform/php-docs-samples#320]
Deployed wordpress using php-docs-sample script on standard environment. 

I am using popular Ninja Form plugin for Wordpress to create contact form.

My options 
'Use App Engine Email Service' - > Checked

e-mail configured is gmail account of registered administrator for google application. (myname@gmail.com)

The e-mails are reported to be successfully send - but never received.

How can I go about debugging this issue?

**Comment by tmatsuo** [comment]
They seems to have a troubleshooting guide at:
https://ninjaforms.com/docs/troubleshooting-email-problems/

Have you followed them?

**Comment by meera** [comment]
Thanks that worked.
Troubleshooting guide states to set e-mail address from same domain name. 
I left default e-mail as blank is and set From Address in ninja form as   wordpress@<appid>.appspot.com - and the e-mail started working.

-Meera
