### ISSUE TITLE
Audio 'content' cannot be longer than 1 min? Audio have only 58sec of duration!

### ISSUE THREAD

**Issue by lgXenos** [GoogleCloudPlatform/php-docs-samples#331]
Hi
I'm try to recognise my audio. But the server of Google return error:
`{
  "error": {
    "code": 400,
    "message": "Audio 'content' cannot be longer than 1 min. For long audio, use the 'uri' parameter to specify a file.",
    "status": "INVALID_ARGUMENT"
  }
}`

But! If I'm request for file info, what I'm can see?

> $ soxi ./sample.flac
> 
> Input File     : './sample.flac'
> Channels       : 1
> Sample Rate    : 8000
> Precision      : 16-bit
> Duration       : 00:00:58.77 = 470121 samples ~ 4407.38 CDDA sectors
> File Size      : 660k
> Bit Rate       : 89.8k
> Sample Encoding: 16-bit FLAC
> Comment        : 'Comment=Processed by SoX'

Why 59 sec great than 60 sec ?

**Comment by bshaffer** [comment]
This is an issue with the API and not with this library, so I'm closing it.

I imagine it has to do with the file size, so it may be a few seconds off. You can use the synchronous call, or use a GCS bucket.
