### ISSUE TITLE
Wordpress: App Engine Custom domains break without SSL Certificate due to wp-config.php "Use https on production"

### ISSUE THREAD

**Issue by remy-actual** [GoogleCloudPlatform/php-docs-samples#338]
I'm serving my Wordpress site at http://wordpress.rootandflow.com added under  
App Engine > settings > custom domains

The subdomain works fine, but unfortunately all of the Wordpress generated links are broken -- they're being prefixed with 'https'

Front-end and admin area still work fine using the appspot domain.

From wp-config.php

```php
// $onGae is true on production.
$onGae = (getenv('GAE_VERSION') !== false);
// ...
// Determine HTTP or HTTPS, then set WP_SITEURL and WP_HOME
if (isset($_SERVER['HTTP_HOST'])) {
    define('HTTP_HOST', $_SERVER['HTTP_HOST']);
} else {
    define('HTTP_HOST', 'localhost');
}
// Use https on production.
define('WP_HOME', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);
define('WP_SITEURL', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);

// Force SSL for admin pages
define('FORCE_SSL_ADMIN', $onGae);
```

Any way to tweak this to use 'http' when requested on a non-appspot domain?

**Comment by tmatsuo** [comment]
Maybe you can comment out those 2 lines as follows:

```
// Use https on production.
// define('WP_HOME', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);
// define('WP_SITEURL', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);
```

**Comment by remy-actual** [comment]
Tried commenting out the above.
Unfortunately the on-page links are now generated with the PROJECT.appspot.com domain 😕

**Comment by tmatsuo** [comment]
@remy-actual 

Go to /options-general.php and configure the `WordPress Address (URL)` and `Site Address (URL)`

**Comment by remy-actual** [comment]
Here's what worked for me:

In wp-config.php >>

```php
// $onGae is true on production.
$onGae = (getenv('GAE_VERSION') !== false);

// Disable pseudo cron behavior
define('DISABLE_WP_CRON', true);

// Determine HTTP or HTTPS, then set WP_SITEURL and WP_HOME
if (isset($_SERVER['HTTP_HOST'])) {
    define('HTTP_HOST', $_SERVER['HTTP_HOST']);
} else {
    define('HTTP_HOST', 'localhost');
}
// Use https on production.
// define('WP_HOME', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);
   define('WP_SITEURL', $onGae ? 'https://' . HTTP_HOST : 'http://' . HTTP_HOST);

// Force SSL for admin pages
define('FORCE_SSL_ADMIN', $onGae);
```

This allows the application to set the backend to the PROJECT.appspot.com domain with SSL on production, and to localhost on dev -- if `WP_HOME` is not set dynamically in wp-config, requests to localhost get redirected to the production app domain. 

![wp-options-url](https://cloud.githubusercontent.com/assets/952821/24576053/843832da-1669-11e7-8e5a-029b7bcedbba.png)
