### ISSUE TITLE
Async command results in output being shown twice

### ISSUE THREAD

**Issue by danaharon** [GoogleCloudPlatform/php-docs-samples#349]
(env) daharon-macpro:api daharon$ php speech.php transcribe test/data/audio32KHz.flac --encoding FLAC --sample-rate 32000 --async
Waiting for operation to complete
Waiting for operation to complete
Array
(
    [0] => Array
        (
            [transcript] => how old is the Brooklyn Bridge
            [confidence] => 0.98267895
        )

)
Array
(
    [0] => Array
        (
            [transcript] => how old is the Brooklyn Bridge
            [confidence] => 0.98267895
        )

)

**Comment by bshaffer** [comment]
thanks for catching this!
