### ISSUE TITLE
Speech Streaming Sample fails with files longer than 6 seconds (but work fine with NodeJS streaming sample)

### ISSUE THREAD

**Issue by rcoenen** [GoogleCloudPlatform/php-docs-samples#354]
Files longer than 6 seconds (exactly) fail in the PHP streaming sample, however, the same sample works fine in the Node.JS streaming sample

**WORKS:** Audio not longer than max 6 seconds
`php speech.php transcribe /Users/megasmasher/Development/audio/LINEAR16_16KHz_mono_sample_6seconds.raw --encoding LINEAR16 --sample-rate 16000 --stream`

**FAILS:** audio longer than 6 seconds
`php speech.php transcribe /Users/megasmasher/Development/audio/LINEAR16_16KHz_mono_sample_7seconds.raw --encoding LINEAR16 --sample-rate 16000 --stream`

Throws a _[Google\GAX\ApiException] Invalid 'audio_content': too long._

**However** testing the same audio (longer than 6 seconds) with the Node.JS Streaming Sample works just fine:
`node recognize.js stream /Users/megasmasher/Development/audio/LINEAR16_16KHz_mono_sample_7seconds.raw  -e LINEAR16 -r 16000`

**Comment by bshaffer** [comment]
hey @rcoenen ! Thank you for reporting this issue. We will look into it.
In the meantime, I suggest using the `async` option:

```
php speech.php transcribe /path/to/LINEAR16_16KHz_mono_sample_6seconds.raw --encoding LINEAR16 --sample-rate 16000 --async
```

Also try uploading the file first to a GCS bucket:

```
gsutil cp /path/to/LINEAR16_16KHz_mono_sample_6seconds.raw gs://YOUR-BUCKET
php speech.php transcribe gs://YOUR-BUCKET/LINEAR16_16KHz_mono_sample_6seconds.raw --encoding LINEAR16 --sample-rate 16000 --async
```

**Comment by bshaffer** [comment]
This can be done now by using the STREAMING sample for php in the `speech/` directory:
```php
php src/streaming_recognize.php
```
