### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by fenixsolorzano** [GoogleCloudPlatform/php-docs-samples#356]
I followed all the steps to setup Wordpress using 1st gen CloudSQL, but there's no step to upload the local database to GCS.

CloudSQL Proxy is only available for 2nd gen instances, so... what's the way to go here to get the database uploaded or synched?

**Comment by feniixx** [comment]
Sorry, I followed the steps again, now it is working, I'm just having trouble with uploading a theme locally.

I also wanted to know what are the steps to follow if a collegue wants to work on the project, when downloading the project it downloads a folder called __static__, what's that supposed to be?

**Comment by jgacuca567** [comment]
@feniixx are you still having a problem with locally uploading themes?

How about deploying then your team can work on the domain instead?

**Comment by bshaffer** [comment]
We have removed instructions for Cloud SQL gen 1, as Cloud SQL gen 2 is highly recommended.
