### ISSUE TITLE
Memcache on flexible environnement

### ISSUE THREAD

**Issue by jflefebvre06** [GoogleCloudPlatform/php-docs-samples#357]
Hello,

On the pages https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible and https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/wordpress it is written :
For flexible environment
 - Batcache Manager
 - GCS media plugin

but at the end of installation I have not the 2 files : 
wordpress/wp-content/plugins/batcache/advanced-cache.php
wordpress/wp-content/plugins/memcached/object-cache.php

In the file WordPressSetup.php we can see that BATCACHE and MEMCACHED are only installed on standard STANDARD_ENV (if ($env === self::STANDARD_ENV) { ... )

Can we really use memcache on flexible environnement ?

Thanks

**Comment by bshaffer** [comment]
Memcache is not supported as an App Engine service, but you can follow [these instructions](https://cloud.google.com/appengine/docs/flexible/php/using-redislabs-memcache) to deploy a memcache cloud and use that.
