### ISSUE TITLE
How to perform streaming recognition in PHP?

### ISSUE THREAD

**Issue by plonknimbuzz** [GoogleCloudPlatform/php-docs-samples#375]
i try speech api around 2 weeks. i can perform Synchronousrecognition PHP, Asynchronous PHP and [web speech API live from mic](https://www.google.com/intl/en/chrome/demos/speech.html).

i try this: `php speech.php transcribe test/data/audio32KHz.flac --encoding FLAC --sample-rate 32000 --stream`
this return successfully. But where the streaming?
its more like : `php speech.php transcribe test/data/audio32KHz.flac --encoding FLAC --sample-rate 32000` (simple Synchronous)

what is the different?
but because its seems Synchronous need to wait all of audio, and streaming like no need to wait or transcribe part by part. so i struggle to know about this,
in past 2 days ago until now, i try different audio and i got so many error return.
-- too long
-- too fast
-- too slow 

summary: i cant perform streaming api with any audio that i have. wtf

i'm using ffmpeg to convert all audio to flac 16KHz which work with sync and async as well.
`"./ffmpeg -i '$pathInput' -c:a flac -ar 16000 -ac 1 -sample_fmt s16 '$pathOutput'"`
and i think is not a problem since sync and async worked with all of them.

about 1 hour ago i find this issue: https://github.com/GoogleCloudPlatform/php-docs-samples/issues/354
and that save my hour. streaming api only accept 6 seconds audio.
i try use my mic to record then convert it to flac. 
yap. finally i make my first example audio in streaming api after 2 days ><

this happen because i dont find any docs write it (too long, too fast, too slow) even in google cloud website.

but, wait. why i can only transcribe 6 sec audio with streaming recognition which means "**unlimited duration**" or mor than async duration (my expectation).

thank for any help. 

NOTE: i try nodejs example too

**Comment by bshaffer** [comment]
See [this example](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech/src/streaming_recognize.php) for streaming recognize. use the command `php speech.php transcribe-stream`. Streaming is only available with the `grpc.so` extension enabled.
