### ISSUE TITLE
Drupal instructions throw an error

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#39]
It's about the last part of the [README](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/managed_vms/drupal8/README.md).

```
~/bin/drupal config:edit                                       
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  
```
                                                        
Also, the integration test on our jenkins fails with:

```
+ /workspace/php-docs-samples/managed_vms/drupal8/tests/drupal cache:rebuild all
  [InvalidArgumentException]                               
  There are no commands defined in the "cache" namespace. 
```

Do I miss something?

**Comment by bshaffer** [comment]
This has been fixed - it was because the `site:install` command was failing due to the missing `gd`, `mysql`, and `pdo_mysql` extensions
