### ISSUE TITLE
[Question] Standard Environment

### ISSUE THREAD

**Issue by Maxikq** [GoogleCloudPlatform/php-docs-samples#435]
Is it possible to integrate in the same way Google Cloud Datastore with Google App Engine using Standard Environment?

**Comment by bshaffer** [comment]
Yes! You can use the [`google/cloud-datastore`](https://github.com/googleapis/google-cloud-php-datastore) library:

```sh
composer require google/cloud-datastore
```

Check out [the docs](https://cloud.google.com/datastore/docs/concepts/queries) for samples and documentation.
