### ISSUE TITLE
SQLSTATE[HY000] [2002] Unable to connect

### ISSUE THREAD

**Issue by jgacuca567** [GoogleCloudPlatform/php-docs-samples#439]
Following the tutorial from https://cloud.google.com/php/getting-started/using-cloud-sql-with-mysql, I am unable to continue to the next step. 

Steps I have done so far,
1. Downloaded MySQL Local Proxy
2. Created a database and a user

This are the errors I keep receiving

<img width="1194" alt="googlecloudproblem" src="https://user-images.githubusercontent.com/4000076/30085600-3b811fa2-9265-11e7-8e1d-63b4adae43cf.png">

<img width="1179" alt="screen shot 2017-09-05 at 6 05 36 pm" src="https://user-images.githubusercontent.com/4000076/30085551-f4b1d0e4-9264-11e7-96c6-ce3b0493270b.png">
<img width="1132" alt="screen shot 2017-09-05 at 6 05 46 pm" src="https://user-images.githubusercontent.com/4000076/30085552-f4b72ea4-9264-11e7-8b4d-96279554f475.png">

**Comment by moneal** [comment]
Are you getting this locally or on GAE? Are you using `gcloud beta app deploy` to deploy to GAE?

**Comment by jgacuca567** [comment]
@moneal I am getting this locally therefore unable to deploy.

**Comment by moneal** [comment]
Are you getting any messages from `cloud_sql_proxy`? It should look something like this:
```
$ cloud_sql_proxy -instances=bookshelf-app-174223:us-east4:bookshelftest=tcp:3306
2017/09/15 13:15:05 Listening on 127.0.0.1:3306 for bookshelf-app-174223:us-east4:bookshelftest
2017/09/15 13:15:05 Ready for new connections
```
This creates a proxy on your localhost `127.0.0.1` on port `3306` I run my local proxy on port `3308` to avoid conflicts. You can now test your connection with any DB tool you like. This is what the connection looks like with Sequel Pro:

![sequel_pro](https://user-images.githubusercontent.com/46388/30501917-0e81473c-9a19-11e7-9a29-7a29543d7b3a.png)

You can test the connection and `cloud_sql_proxy` should output something like this:
```
2017/09/15 13:15:08 New connection for "bookshelf-app-174223:us-east4:bookshelftest"
2017/09/15 13:15:10 Client closed local connection on 127.0.0.1:3306
```

If your authentication details are not correct the instance closes the connection not the client and it looks like this:
```
2017/09/15 13:15:25 New connection for "bookshelf-app-174223:us-east4:bookshelftest"
2017/09/15 13:15:26 Instance bookshelf-app-174223:us-east4:bookshelftest closed connection
```

When testing your app locally using `cloud_sql_proxy` the host needs to be `127.0.0.1` or the IP it told you it was listening on. I'm guessing the IP you have shown in your config is your cloudsql instance. That rejects connections by default. You need to whitelist outside IP addresses that you want to connect with. The purpose of `cloud_sql_proxy` is to avoid connecting like that.

P.S. I changed the output of my examples to match your config. I can't connect to your instances.

**Comment by bshaffer** [comment]
Yes, the IP should represent localhost, where the proxy is running. I imagine this is the issue.

**Comment by jgacuca567** [comment]
@bshaffer @moneal 

I followed your example and changed the ip to `127.0.0.1` and I was able to get it to work, see screenshots below. 

<img width="1594" alt="screen shot 2017-09-16 at 10 41 35 am" src="https://user-images.githubusercontent.com/4000076/30513121-e47be3b2-9acb-11e7-8cf1-76db1af2f7ae.png">
<img width="2552" alt="screen shot 2017-09-16 at 10 41 47 am" src="https://user-images.githubusercontent.com/4000076/30513122-e47f8de6-9acb-11e7-8aaa-379c1e850c2e.png">

**Comment by bshaffer** [comment]
Woohoo, glad to hear it! Thanks for your help @moneal
