### ISSUE TITLE
The requested PHP extension gd is missing from your system [Flexible environment]

### ISSUE THREAD

**Issue by mgallegos** [GoogleCloudPlatform/php-docs-samples#446]
I haven't had this issue before, but today I started getting the error: "The requested PHP extension gd is missing from your system Flexible environment" when trying to the deploy my application.

My php.ini looks likes this:

> extension=gd.so
> extension=curl.so
> extension=imagick.so
> extension=fileinfo.so

I'm getting the following output:

> Loading composer repositories with package information
> Installing dependencies from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for dompdf/dompdf v0.8.0 -> satisfiable by dompdf/dompdf[v0.8.0].
>     - dompdf/dompdf v0.8.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
>   Problem 2
>     - dompdf/dompdf v0.8.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
>     - barryvdh/laravel-dompdf v0.8.1 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.0].
>     - Installation request for barryvdh/laravel-dompdf v0.8.1 -> satisfiable by barryvdh/laravel-dompdf[v0.8.1].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /opt/php56/lib/php-cli.ini
>     - /opt/php56/lib/ext.enabled/ext-apcu.ini
>     - /opt/php56/lib/ext.enabled/ext-json.ini
>     - /opt/php56/lib/ext.enabled/ext-libsodium.ini
>     - /opt/php56/lib/ext.enabled/ext-mailparse.ini
>     - /opt/php56/lib/ext.enabled/ext-memcached.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> The command '/bin/sh -c /build-scripts/composer.sh' returned a non-zero code: 2
> ERROR
> ERROR: build step "gcr.io/cloud-builders/docker@sha256:f0bdb31bcf87dad333755477c02916411d5ac9ea891497d304a360b01f2fcb10" failed: exit status 2

**Comment by bshaffer** [comment]
You need to add "ext-gd": "*" to your application's `composer.json`:

```
composer require "ext-gd:*" --ignore-platform-reqs
```

It doesn't matter if `gd` is enabled in your local PHP install, the flexible environment is built using your `composer.json` file, so you need to add it there.

**Comment by anirnet** [comment]
> You need to add "ext-gd": "*" to your application's `composer.json`:
> 
> ```
> composer require "ext-gd:*" --ignore-platform-reqs
> ```
> It doesn't matter if `gd` is enabled in your local PHP install, the flexible environment is built using your `composer.json` and `app.yaml` files, so you need to add it there.

finally after 7 days of searching, thanks bro

**Comment by Chandra0505** [comment]
Can anyone help while executing this command `php composer require "ext-gd:*" --ignore-platform-reqs`
I'm getting is error:
 [InvalidArgumentException]
  Could not find a matching version of package ext-gd. Check the package spelling, your version constraint and that t
  he package is available in a stability which matches your minimum-stability (stable).

I' m trying to install mpdf via composer so there is need of gd driver.

My system configuration is window 10.

**Comment by jasmohan** [comment]
> You need to add "ext-gd": "*" to your application's `composer.json`:
> 
> ```
> composer require "ext-gd:*" --ignore-platform-reqs
> ```
> 
> It doesn't matter if `gd` is enabled in your local PHP install, the flexible environment is built using your `composer.json` and `app.yaml` files, so you need to add it there.

I did what you above. I am trying to run composer require phpoffice/phpspreadsheet
but I receive the following error every time I try to run this command:
 Problem 1
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - phpoffice/phpspreadsheet 1.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - phpoffice/phpspreadsheet 1.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for phpoffice/phpspreadsheet 1.7.0 -> satisfiable by phpoffice/phpspreadsheet[1.7.0].

please reply if you have any clue how to resolve this.

For your info:
1. this is working perfectly fine on my local machine (mac + Xamp)
2. Not working on my server (AWS EC2 - Os = linux ami 2)
3. tried rebooting my instance as well

**Comment by daodhoa** [comment]
> > You need to add "ext-gd": "*" to your application's `composer.json`:
> > ```
> > composer require "ext-gd:*" --ignore-platform-reqs
> > ```
> > 
> > 
> > It doesn't matter if `gd` is enabled in your local PHP install, the flexible environment is built using your `composer.json` and `app.yaml` files, so you need to add it there.
> 
> I followed the steps suggested above. I am trying to run composer require phpoffice/phpspreadsheet
> but I receive the following error every time I try to run this command:
> Problem 1
> - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
> Problem 2
> - phpoffice/phpspreadsheet 1.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
> - phpoffice/phpspreadsheet 1.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
> - Installation request for phpoffice/phpspreadsheet 1.7.0 -> satisfiable by phpoffice/phpspreadsheet[1.7.0].
> 
> please reply if you have any clue how to resolve this.
> 
> For your info:
> 
> 1. this is working perfectly fine on my local machine (mac + Xamp)
> 2. Not working on my server (AWS EC2 - Os = linux ami 2)
> 3. tried rebooting my instance as well

I have a same issue as you. Did you resolve it?? Help me, please

**Comment by OupaMoloi** [comment]
@daodhoa did you manage to get a solution relating this issue, I have the same issue

**Comment by OupaMoloi** [comment]
Just resolved it OS: Windows 
I had to add extension=php_gd2.dll to the bottom of my php.ini file.

The dll was already there in the ext folder

**Comment by itsdeo** [comment]
While installing a maatwebsite/excel package on the server it gives below error. Code is deploying using CircleCI. I checked on the server gd extension is already enabled. Can anyone help me on this please?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpoffice/phpspreadsheet 1.14.1 -> satisfiable by phpoffice/phpspreadsheet[1.14.1].
    - phpoffice/phpspreadsheet 1.14.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 2
    - phpoffice/phpspreadsheet 1.14.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - maatwebsite/excel 3.1.21 requires phpoffice/phpspreadsheet ^1.14 -> satisfiable by phpoffice/phpspreadsheet[1.14.1].
    - Installation request for maatwebsite/excel 3.1.21 -> satisfiable by maatwebsite/excel[3.1.21].

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Exited with code exit status 2
CircleCI received exit code 2

**Comment by Daespinosag** [comment]
use 
sudo apt-get install phpX.X-gd

change php.X.X for your php version.

**Comment by Marcelino15** [comment]
> 
> 
> Just resolved it OS: Windows
> I had to add extension=php_gd2.dll to the bottom of my php.ini file.
> 
> The dll was already there in the ext folder

it's work thank you

**Comment by nadia-am** [comment]
i remove ; from php .ini line `extension=gd` and run `composer require "ext-gd:*" --ignore-platform-reqs` but none of them works! i still get error `GD Library extension not available with this PHP installation.`

**Comment by alvin-c-h** [comment]
still error

**Comment by bshaffer** [comment]
@nadia-am @alvin-c-h This solution is for the Google Cloud App Engine Flexible environment. If you're encountering this error outside this environment, the solution will be different. You'll need to install / enable the GD extension for that environment.

**Comment by NeverioDev** [comment]
Hello try going to php.ini then look for ;extension=gd
Remove the ;
this is how i made mine work

**Comment by Danendra10** [comment]
Hi!!

For me, this error would show if you haven't uncoment the "extension=gd" in your php.ini file, in my case, I'm using PHP 8.1, in PHP 7.* you will find the extension called "gd2" just uncomment it, and you're ready to go

**Comment by Afssatou** [comment]
Bonjour moi j'ai toujours le même problème et aucune méthode citée en haut n'a résolu le mien
