### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format

### ISSUE THREAD

**Issue by jgacuca567** [GoogleCloudPlatform/php-docs-samples#448]
@ryanmats @bshaffer @tmatsuo 

Following Issue https://github.com/GoogleCloudPlatform/php-docs-samples/issues/439 

I was able to get to the next step. However the datetime issue is popping up. 

When I clicked Add New Book, The Date is shown by Default

<img width="1227" alt="screen shot 2017-09-16 at 11 45 49 am" src="https://user-images.githubusercontent.com/4000076/30513642-9e6a0986-9ad4-11e7-9861-842251f8527a.png">

<img width="1275" alt="screen shot 2017-09-16 at 11 43 52 am" src="https://user-images.githubusercontent.com/4000076/30513626-68608c52-9ad4-11e7-9161-cfc873902754.png">
<img width="1223" alt="screen shot 2017-09-16 at 11 43 59 am" src="https://user-images.githubusercontent.com/4000076/30513625-685ef806-9ad4-11e7-981c-2da277616c60.png">

**Comment by tmatsuo** [comment]
@jgacuca567 Is this happening locally?

**Comment by jgacuca567** [comment]
Yes.

**Comment by tmatsuo** [comment]
@jgacuca567 
I think this is more related to https://github.com/googlecloudplatform/getting-started-php
Can you move the issue to that repo?

**Comment by jgacuca567** [comment]
@tmatsuo done.
