### ISSUE TITLE
Create and configure a Cloud SQL 1st generation instance

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#451]
This section is incomplete. It needs to provide explicit instructions with pictures on how to carry out these tasks. E.g. creating a database.

```
Create and configure a Cloud SQL 1st generation instance(for standard environment)

Go to the SQL settings in the Cloud Console and create an instance wp and database named wp. Go to the Access Control -> Users, then change the password for root@localhost. You will use this password for accessing from App Engine application.

Also create the wp database in the local mysql server. The local mysql instance is required to run wp-cli tool for installing/upgrading plugins and themes.
```

**Comment by elharo** [comment]
" Go to the Access Control -> Users,"

I cannot find this. There is a Users tab under the instance. Probably pantheon layout has changed.

**Comment by elharo** [comment]
"Also create the wp database in the local mysql server."

This needs a **lot** more detail. I'm going to have to google for other pages to figure this part out.

**Comment by bshaffer** [comment]
The Wordpress examples have been updated. They now use CloudSQL Generation 2 and they have better documentation. See [here](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/wordpress)
