### ISSUE TITLE
how to set the environment variable GCLOUD_PROJECT to your project ID?

### ISSUE THREAD

**Issue by tammyruihuang** [GoogleCloudPlatform/php-docs-samples#456]
I tried to run "gcloud init" to setup my default project and it was done OK, however, I still see this error when I run the samples. I then tried to use "gcloud config set project MY_PROJECT_ID" and it was set. I could see my one and only project in "gcloud projects list". However, even after I did all these, I still see this error message. Is there any other way to solve this issue?

**Comment by jgacuca567** [comment]
@tammyruihuang Post a screenshot showing the error.

**Comment by tammyruihuang** [comment]
![error screenshot](https://user-images.githubusercontent.com/25968500/30872836-6778fdfa-a2b9-11e7-8f4a-210bd0c895be.png)

Thanks @jgacuca567 !

**Comment by jgacuca567** [comment]
After trying `gcloud auth application-default login` did you succeed in logging in?

**Comment by tammyruihuang** [comment]
I think so. I got the following message.
![error screenshot - 3](https://user-images.githubusercontent.com/25968500/30876239-f6452f18-a2c3-11e7-978a-3765aa38636d.png)

However, after this, I tried to run the command again but still got the same error message:
![error screenshot - 2](https://user-images.githubusercontent.com/25968500/30876261-098ac36c-a2c4-11e7-9d1c-117cb5069949.png)

**Comment by bshaffer** [comment]
Sorry, yes this is an annoying aspect to these samples and we are trying to fix it by explicitly passing the project ID in for most samples. For all other samples, simply setting the environment variable `GCLOUD_PROJECT` will do the trick:

```sh
# bash
export GCLOUD_PROJECT=YOUR_PROJECT_ID
```
```php
# php
putenv('GCLOUD_PROJECT=' . $yourProjectId);
```

**Comment by tammyruihuang** [comment]
Sorry I am kind of new to GC products. How do I set the variable as you mentioned? Where can I find the bash file? Is the php file you mentioned the php.ini? Thanks for your help!

**Comment by jgacuca567** [comment]
@bshaffer, @tmatsuo, I was able to deploy locally after adding the `putenv` in my `wp-config.php`. However when I deploy to the domain while the plugin has been activated, it does not work on my domain. What am I missing?
