### ISSUE TITLE
Post data to Google Natural Language API via REST 

### ISSUE THREAD

**Issue by Vshri** [GoogleCloudPlatform/php-docs-samples#460]
Hi,

I am stuck in sending post request to google Natural language, below is my code

        APIKEY='-------------------------------';

        $.ajax({

              type        : "POST",

            url         : "https://language.googleapis.com/v1/documents:analyzeEntitySentiment?key="+APIKEY,

            ContentType : "application/json",

            dataType    : 'json',

            data        : { "document": 
                                        {   "type": "PLAIN_TEXT",
                                            "content": 'Hello everyone'},
                           "encodingType": 'UTF8'},

            success     : function(_result){         
                if (_result) {    
                    alert('SUCCESS');
                    $rowsContainer.html(_result); 
                }else{
                    alert('ERROR');
                    $rowsContainer.html(_result); 
                }
            },
            error       : function(_result){
                $rowsContainer.append(_result);
            }
        });
   
Error:

    "code": 400,

    "message": "Invalid JSON payload received. Unknown name \"document[type]\": Cannot bind query parameter. Field 'document[type]' could not be found in request message.\nInvalid JSON payload received.Unknown name \"document[content]\": Cannot bind query parameter. Field 'document[content]' could not be found in request message.",

    "status": "INVALID_ARGUMENT",

    "details": [
      {

        "@type": "type.googleapis.com/google.rpc.BadRequest",

        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"document[type]\": Cannot bind query parameter. Field 'document[type]' could not be found in request message."
          },
          {
            "description": "Invalid JSON payload received. Unknown name \"document[content]\": Cannot bind query parameter. Field 'document[content]' could not be found in request message."
          }

        ]

      }
    ]}

I know I am wrong somewhere but don't know where, can anyone help me?

Thanks!

**Comment by bshaffer** [comment]
Hello,
Sorry this repository is for PHP. Try filing this in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues instead. In general, it would seem that your "data" JSON is invalid. I assume it is not declared correctly in the AJAX call. You could try the following instead:

```javascript
$.ajax({
        type        : "POST",
        url         : "https://language.googleapis.com/v1/documents:analyzeEntitySentiment?key="+APIKEY,
        ContentType : "application/json",
        dataType    : 'json',
        data        : { document:
                             {  type: "PLAIN_TEXT",
                                content: 'Hello everyone'},
                        encodingType: 'UTF8'},
        success     : function(_result){         
            if (_result) {    
                alert('SUCCESS');
                $rowsContainer.html(_result); 
            }else{
                alert('ERROR');
                $rowsContainer.html(_result); 
            }
        },
        error       : function(_result){
            $rowsContainer.append(_result);
        }
    });
```
