### ISSUE TITLE
 unable to decompress gzipped phar archive "/tmp/wordpress-4.8.2.tar.gz" to temporary file 

### ISSUE THREAD

**Issue by ramimmadi** [GoogleCloudPlatform/php-docs-samples#462]
I am trying to do the codelabs.. Running Wordpress on GAE. I am facing the error:  _unable to decompress gzipped phar archive "/tmp/wordpress-4.8.2.tar.gz"_ to temporary file while using thethe following command::: _php wordpress-helper.php setup -d ${HOME}/my-wordpress-project_

**Comment by roku6185** [comment]
I get the same error

**Comment by jgacuca567** [comment]
@ramimmadi and @roku6185 are you able to post a video showing how you got the error? 4.8.2 is working fine.

**Comment by roku6185** [comment]
[wordpress_appengine_install_error.zip](https://github.com/GoogleCloudPlatform/php-docs-samples/files/1433862/wordpress_appengine_install_error.zip)

**Comment by jgacuca567** [comment]
@roku6185 Why not use **Flexible Environment** 
I tested it with Flexible and it works. Let me know if you are getting any error.

**Comment by roku6185** [comment]
I want to use AppEngine Stadard for various reasons and it is selectable as a choice in the installer. Clearly, the installation doesn't work for me as you can see. To make it work, If I manually edit php-docs-samples/appengine/wordpress/src/WordPressSetup.php and set LATEST_WP to **4.8.1**.

**Comment by tmatsuo** [comment]
Seems like some WordPress archive for the version `4.8.2` have a problem.

You can explicitly specify the archive url by `--wordpress_url` option.

I would close this as wai
