### ISSUE TITLE
quickstart == deadstart

### ISSUE THREAD

**Issue by x011** [GoogleCloudPlatform/php-docs-samples#465]
Why would someone publish a `quickstart.php` that doesn't work out of the box ?
It doesn't seem _very googlish_ to me.

Can we use the fix of the following error to make a better `quickstart.php` ?
`
Fatal error: Uncaught Google\Cloud\Core\Exception\ServiceException: Could not load the default credentials.`

**Comment by bshaffer** [comment]
Hey there, you will need to download the service account credentials from the Google Developer Console and set them to the environment variable GOOGLE_APPLICATION_CREDENTIALS

Which quickstart are you trying to use? The instructions on setting up authentication should be in the readme.

Also, the proper adjective is *googley*, not *googlish* 😁

**Comment by tmatsuo** [comment]
Needs more info
