### ISSUE TITLE
Untarballing WordPress version 4.8.2 causes wordpress-helper.php to fail

### ISSUE THREAD

**Issue by whitecoop** [GoogleCloudPlatform/php-docs-samples#467]
While going through the [WordPress on GAE Flexible Environment guide](https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible), I go this error when running step `4. Run the helper script`:

```
$ php wordpress-helper.php setup -n \
    -d ./wordpress-project \
    --db_instance=tutorial-sql-instance \
    --db_name=tutorialdb \
    --db_user=tutorial-user \
    -p [MY_PROJECT_ID] \
    --db_password=[MY_DATABASE_PASSWORD]
Re-using a directory /[redacted]/php-docs-samples/appengine/wordpress/./wordpress-project.
Creating a new project for: Flexible Environment
Using a db_region: us-central1
Downloading the WordPress archive...


  [UnexpectedValueException]
  unable to decompress gzipped phar archive "/tmp/wordpress-4.8.2.tar.gz" to temporary file
```

After a bit of hunting, there's [apparently some issue](https://github.com/wp-cli/wp-cli/issues/4370#issuecomment-330999005) with untarballing v4.8.2 of WordPress (v4.8.1 works fine).

So I edited [this line](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/wordpress/src/WordPressSetup.php#L32) from
```
    const LATEST_WP = 'https://wordpress.org/wordpress-4.8.2.tar.gz';
```

to

```
    const LATEST_WP = 'https://wordpress.org/wordpress-4.8.1.tar.gz';
```

and the build in step number 4 of [the guide](https://cloud.google.com/php/tutorials/wordpress-app-engine-flexible) succeeded.

I'd recommend reverting the version of WP back to 4.8.1 till this issue is fixed upstream. As it stands now, it doesn't run correctly out of the box.

Also, the first thing I tried was changing from PHP 7.1 to 7.0, but that didn't do anything -- hence the big hunt above ☝️  😄 .

**Comment by tmatsuo** [comment]
I think it's obsolete
