### ISSUE TITLE
show this message only if the directory exists. 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#470]
This is in the wordpress-helper setup script.

"We will use the directory: ~/wordpress-experiment. If the directory exists, we will override the contents. Do you want to continue? (Y/n)"

It would be better to show this message only if the directory exists, and perhaps make N the default.

**Comment by bshaffer** [comment]
I am moving this request to `GoogleCloudPlatform/php-tools` as this is where the WordPress helper now lives.
