### ISSUE TITLE
Make standard environment the default for wordpress

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#471]
Please select the App Engine Environment (defaults to Flexible Environment)
  [0] Flexible Environment
  [1] Standard Environment

Please contact me internally if the reason isn't apparent.

**Comment by John9570** [comment]
Definitely Agree.

**Comment by bshaffer** [comment]
Please let us know why you believe it is important to default to standard!

**Comment by John9570** [comment]
My understanding is that it would significantly reduce the cost of hosting wordpress on GAE. The standard environment has a free tier

**Comment by bshaffer** [comment]
The default `wp-gae` tool (installable using `composer install --global google/cloud-tools` and calling `vendor/bin/wp-gae`) now only uses App Engine Standard.
