### ISSUE TITLE
Unix file path conventions on wordpress install

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#472]
When asked where to put the files I said 

Please enter a directory path for the new project (defaults to my-wordpress-project):~/wordpress-experiment
We will use the directory: ~/wordpress-experiment. If the directory exists, we will override the contents. Do you want to continue? (Y/n)

and here's where it went:

Re-using a directory /Users/elharo/php-docs-samples/appengine/wordpress/~/wordpress-experiment.

I expected it to go in my home directory: ~.

**Comment by bshaffer** [comment]
I am moving this request to `GoogleCloudPlatform/php-tools` as this is  where the WordPress helper now lives.
