### ISSUE TITLE
Which db_password? in wordpress helper

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#487]
When I get to Please enter db_password, there are two, one for the root user for the database and one for the wp user. These are different but the message doesn't tell me which one is needed here:

```
Downloaded App Engine WordPress plugin.
Please enter project_id (mandatory input): mokka-186313
Please enter db_instance (defaults to 'wp'): 
Please enter db_name (defaults to 'wp'): 
Please enter db_user (defaults to 'wp'): 
Please enter db_password (mandatory input): 
```

This may explain why my first attempt failed. I suspect what we need is the wp user's password, but I'm not sure.

**Comment by bshaffer** [comment]
The admin password is created when you set up your instance after it's deployed to App Engine. So no prompt for admin password is necessary in the tool
