### ISSUE TITLE
Upgrade to 4.9.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#491]
Just installed using the helper and got Wordpress 4.8.2. Not too far out of date, but 4.9.0 is available.

**Comment by tmatsuo** [comment]
Thanks for the report. I think we should use the latest link.

https://wordpress.org/latest.tar.gz

**Comment by tmatsuo** [comment]
#492 should fix this

**Comment by jgacuca567** [comment]
@elharo are you still getting the issue?

**Comment by elharo** [comment]
Haven't tested it since I installed 4.8.2. The upgrade script doesn't work, but that's a separate issue.

**Comment by jgacuca567** [comment]
What issues are you getting when you run the upgrade script?

**Comment by elharo** [comment]
I'm trying to upgrade WordPress on App Engine standard using the wp
cli (since App Engine WP can't use the usual wordpress upgrade
system.)

This dies with

$ vendor/bin/wp core update --path=wordpress
PHP Fatal error:  Class 'Memcache' not found in
/Users/elharo/cafe.elharo.com/wordpress/wp-content/object-cache.php on
line 425
Fatal error: Class 'Memcache' not found in
/Users/elharo/cafe.elharo.com/wordpress/wp-content/object-cache.php on
line 425

The problem seems to be that the memcache module isn't found in the
local PHP install. However I installed with with brew and

```
$ ls /usr/local/etc/php/5.6/conf.d
ext-igbinary.ini ext-memcached.ini
```

Is there a step I missed somewhere to install the Memcache module?

**Comment by elharo** [comment]
OK, got past that bug. I needed to `brew install memcache` instead of `brew install memcached`

Now it's dying with

```
$ vendor/bin/wp core update --path=wordpress
PHP Warning:  require_once(google/appengine/api/urlfetch_service_pb.php): failed to open stream: No such file or directory in /Users/elharo/cafe.elharo.com/wordpress/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72
Warning: require_once(google/appengine/api/urlfetch_service_pb.php): failed to open stream: No such file or directory in /Users/elharo/cafe.elharo.com/wordpress/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72
PHP Fatal error:  require_once(): Failed opening required 'google/appengine/api/urlfetch_service_pb.php' (include_path='.:') in /Users/elharo/cafe.elharo.com/wordpress/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72
Fatal error: require_once(): Failed opening required 'google/appengine/api/urlfetch_service_pb.php' (include_path='.:') in /Users/elharo/cafe.elharo.com/wordpress/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72
```

**Comment by elharo** [comment]
This appears to be https://github.com/GoogleCloudPlatform/php-docs-samples/issues/314
