### ISSUE TITLE
Error Establishing a database Connection after Deploying to Google App Engine 

### ISSUE THREAD

**Issue by jgacuca567** [GoogleCloudPlatform/php-docs-samples#494]
## Steps I have done so far

1. I am running **2nd** generation instance.
2. I am able to connect locally but when I run `gcloud app deploy` I keep getting the error **Error establishing a database connection**
3. I have tried using `root` and a blank password and still does not work. 
4. I have created service permission for the SQL 

See my wp-config.php page as well as the screenshot from cloud.google.com everything matches but still getting the error.

### Screenshots Below 

[![Local Connection of SQL Working][1]][1]

[![My Instance][2]][2]

[![My Users][3]][3]

[![wp-config.php][4]][4][![SQL Instance][5]][5]

  [1]: https://i.stack.imgur.com/mniSB.png
  [2]: https://i.stack.imgur.com/UiQnO.png
  [3]: https://i.stack.imgur.com/UgBZb.png
  [4]: https://i.stack.imgur.com/vxu3E.png
  [5]: https://i.stack.imgur.com/LYmaE.png

**Comment by tmatsuo** [comment]
@jgacuca567 Be careful for putting your password in public.

Can you show me the output of `gcloud info`?

**Comment by tmatsuo** [comment]
@jgacuca567 

I think I reproduced your issue with WordPress 4.9. I think WordPress 4.9 has a bug parsing the DB_HOST when it contains more than 2 colon characters `:` like our case. This issue is already reported at:
https://core.trac.wordpress.org/ticket/42634

It seems like the next version (4.9.1) will fix it.

Meantime, can you use 4.8.2? You can specify the URL of the WordPress archive with `--wordpress-url` option as follows:

```
php wordpress-helper.php setup --wordpress_url https://wordpress.org/wordpress-4.8.2.tar.gz
```

Thanks for the report!

**Comment by tmatsuo** [comment]
Also, the 4.9.1 will be released very soon, according to:
https://make.wordpress.org/core/tag/4-9-1/

**Comment by tmatsuo** [comment]
WordPress 4.9.1 is released. It should fix the issue.

**Comment by jgacuca567** [comment]
@tmatsuo attached is the `gcloud info`

<img width="2560" alt="screen shot 2017-11-29 at 7 00 26 pm" src="https://user-images.githubusercontent.com/4000076/33406114-5f5402e8-d539-11e7-82a9-2a8a8d4e1b46.png">

That was what caused the issue. Everything back to normal. Much much appreciated. Thank You.

**Comment by abhilashst** [comment]
@jgacuca567 I am actually new to Google Cloud and facing the same issue. Could you please guide me to resolve this?

**Comment by sushen** [comment]
I am facing the some problem did it resolve.
