### ISSUE TITLE
[GAE flexible] Compiling views on Laravel 5.2

### ISSUE THREAD

**Issue by mgallegos** [GoogleCloudPlatform/php-docs-samples#495]
I'm getting the following error when trying to load any page on my application:

ErrorException in Filesystem.php line 111:
file_put_contents(/tmp/views/e1d36b90487a7f4f9da639dac1131224a7d2af57.php): failed to open stream: No such file or directory

What is the correct way to handle the compiled views that Laravel generates on GAE flexible?

Is there a way to store the compiled views on google cloud storage?

**Comment by bshaffer** [comment]
The way the tutorial works is to read and write views to `/tmp`. I am not sure why this error would occur.

You could try setting a `gs://<bucket-name>` URL for the views, and then all file streaming functions will use Cloud Storage. This is something we've done before, but it's not an optimal solution. It should be possible to either warm the cache before deployment (so the views are stored locally), which is what we do in the [Symfony AppEngine Starter Project](https://github.com/GoogleCloudPlatform/appengine-symfony-starter-project)

**Comment by mgallegos** [comment]
I'm trying to improve performance on my application, it takes around 8 to 10 seconds to load a page I believe the issue should be that's it takes to long to store the compiled views files because when I load I simple HTML pages it takes up to 2 seconds.

**Comment by tmatsuo** [comment]
Does the directory '/tmp/views' exist?

**Comment by tmatsuo** [comment]
Maybe you can create it in `post-install` command

**Comment by mgallegos** [comment]
I change the directory and it's working now. However I still have the performance issue.

**Comment by tmatsuo** [comment]
@mgallegos 

Do you want to try our (pre-alpha) tracing solution for determining the performance bottleneck?

**Comment by mgallegos** [comment]
ok!

**Comment by tmatsuo** [comment]
@mgallegos Cool.

Add the following dependencies
```
        "ext-opencensus": "*", 
        "opencensus/opencensus": "0.0.4",
        "google/cloud-trace": "^0.3"
```
Then follow the instructions at:
https://github.com/census-instrumentation/opencensus-php/blob/master/examples/laravel/README.md

Then you can see the trace data on the Cloud Console (Go to "Trace")

CCing @chingor13 in case I'm missing something.

Also, what does your app do? Are there lots of RPC calls within your handler?

**Comment by mgallegos** [comment]
It's a ERP software, mostly pages to interact with database tables.

**Comment by tmatsuo** [comment]
@mgallegos Actually it turned out there will be some changes in the Trace lib and the instructions won't work. Can you wait for a week?

**Comment by mgallegos** [comment]
Ok, let me know when can I tested.

About the performance issue, do you believe it will be faster to write the compiled view files in the google cloud storage than in the current directory?

**Comment by tmatsuo** [comment]
If it's caching purpose, I'd use the local disk.
