### ISSUE TITLE
install Memcache deprecated

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#504]
The install Memcache link in php-docs-samples/blob/master/appengine/wordpress/README.md to 
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-memcache-on-ubuntu-12-04#install-memcache

goes to a page that says

```
Status: Deprecated
This article covers a version of Ubuntu that is no longer supported. If you are currently operate a server running Ubuntu 12.04, we highly recommend upgrading or migrating to a supported version of Ubuntu:

Upgrade to Ubuntu 14.04.
Upgrade from Ubuntu 14.04 to Ubuntu 16.04
Migrate the server data to a supported version
```

**Comment by elharo** [comment]
Also it's not clear if this is actually needed or not, and where we're installing it. Locally?

It doesn't seem to be needed for the initial install, but might be needed for the upgrade.

**Comment by elharo** [comment]
Also those instructions are only for Ubuntu. What about Mac OS X and Windows?

**Comment by bshaffer** [comment]
Fixed in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/843
