### ISSUE TITLE
Wordpress on AppEngine does not list all availble regions

### ISSUE THREAD

**Issue by fgrzadkowski** [GoogleCloudPlatform/php-docs-samples#505]
It lists only 4 (e.g. in europe only europe-west1) while AppEngine is available in many more regions.

**Comment by weiyangtan** [comment]
AppEngine constantly introduce new regions for the cloud services, so perhaps allowing the users to enter the **cloud instance connection name** instead of offering a selection of regions maybe more practical to maintain the wordpress-helper script.

**Comment by bshaffer** [comment]
This should now be fixed: https://github.com/GoogleCloudPlatform/php-tools/blob/master/src/Utils/Project.php#L25
