### ISSUE TITLE
BigQuery runQuery function is not excepting a string as the first argument

### ISSUE THREAD

**Issue by ssgtcookie** [GoogleCloudPlatform/php-docs-samples#511]
In the official Google docs, there is an [BQ example](https://cloud.google.com/bigquery/create-simple-app-api) that states that this codeblock can be used to perform a query to BQ:

```
$bigQuery = new BigQueryClient([
    'projectId' => $projectId,
]);
$query = 'SELECT TOP(corpus, 10) as title, COUNT(*) as unique_words ' .
         'FROM [publicdata:samples.shakespeare]';
$options = ['useLegacySql' => true];
$queryResults = $bigQuery->runQuery($query, $options);
```

But this leads to this error:
`Type error: Argument 1 passed to Google\Cloud\BigQuery\BigQueryClient::runQuery() must be an instance of Google\Cloud\BigQuery\JobConfigurationInterface, string given`

The example seems incorrect?

**Comment by ssgtcookie** [comment]
@kurtisvg @remi @raggi @willnorris @proppy @madhusudancs

**Comment by bshaffer** [comment]
@ssgtcookie yes, the examples in the docs use [`google/cloud-bigquery:^0.2`](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/bigquery/shakespeare/composer.json#L3) and you must be using `0.3`.  For `0.3` the sample would look like this:

```php
$query = 'SELECT TOP(corpus, 10) as title, COUNT(*) as unique_words ' .
         'FROM [publicdata:samples.shakespeare]';
$queryJobConfig = $bigQuery->query($query);
$queryResults = $bigQuery->runQuery($queryJobConfig);
```

We will get the samples in the docs updated with the latest version. Thank you for the heads up!

**Comment by bshaffer** [comment]
All of [our BigQuery samples](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/bigquery/api) have long since been updated to use the new API.
