### ISSUE TITLE
db-g1-small is too expensive

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#525]
A db-g1-small Cloud SQL second generation instance  which we recommend for WordPress costs, at the time of this writing, about $25 a month. That doesn't include App Engine or Cloud Storage costs, and there's no free tier for Cloud SQL, unlike App Engine and GCS. This really isn't price competitive with other WordPress hosts.

I've heard some people are successfully running with db-f1-micro instances instead. Explore whether we can recommend this as the default. If so, that brings the price of Cloud SQL down by about 70%.

**Comment by tmatsuo** [comment]
Why do you think it's an issue on the WordPress helper script?

**Comment by elharo** [comment]
Because https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/wordpress/README.md says:

Create a new Cloud SQL for MySQL Second Generation instance with the following
command:

```
$ gcloud sql instances create wp \
  --activation-policy=ALWAYS \
    --tier=db-g1-small
```

I followed along with these docs. If we can get away with db-f1-micro here we should. Or perhaps we can provide some guidance to users about how to choose the right sixed instance for their traffic level.

**Comment by tmatsuo** [comment]
@elharo 

Got it. Let's add some wordings at least

**Comment by tmatsuo** [comment]
@elharo The README was updated. Thanks for the report!
