### ISSUE TITLE
Update authentication setup steps in helloworld README

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/php-docs-samples#527]
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/compute/helloworld#setup-authentication is out of date and needs to be updated.

For example, the first link is https://code.google.com/apis/console/?api=compute but since Google Code has been shut down, it redirects to https://console.developers.google.com/cloud-resource-manager which is confusing.

The rest of the steps probably also need to be reviewed and updated accordingly.

**Comment by tmatsuo** [comment]
Should be covered with #528
