### ISSUE TITLE
[Test] Have faster unit tests in general

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#538]
Many tests are actually accessing the real APIs. We can have unit test style tests for PRs, for faster development cycle, and easier user contribution.

We can still keep the system tests for nightly run.

**Comment by bshaffer** [comment]
We implemented running tests just for affected samples, which means they run pretty fast most of the time, and the whole test suite runs nightly. I believe this is a sufficient solution for now!
