### ISSUE TITLE
[Test] Naming conflict in the pubsub/api/test

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/php-docs-samples#540]
It uses topic and subscription name fetched from environment variable.
It conflicts when you run the tests concurrently.

Maybe we could just append random string to the base name and create those resources during test setup.

**Comment by tmatsuo** [comment]
Also, test message can have unique string in it, rather than "This is a test message"

**Comment by bshaffer** [comment]
This has been fixed by using separate tests in Kokoro for each PHP version.
