### ISSUE TITLE
Can this be used with the Google Play buckets (Google Play app statistics)

### ISSUE THREAD

**Issue by tmillettweather** [GoogleCloudPlatform/php-docs-samples#566]
Can this be used with the Google Play buckets (Google Play app statistics). If so how?

**Comment by bshaffer** [comment]
No, this library is for samples for the client library only. However, check out the [google auth library for PHP](https://github.com/googleapis/google-auth-library-php#call-the-apis) to see how to make authenticated calls to ANY [Google API REST endpoint](https://developers.google.com/android-publisher/api-ref).
