### ISSUE TITLE
Symfony sample test configuration

### ISSUE THREAD

**Issue by lashae** [GoogleCloudPlatform/php-docs-samples#570]
In the symfony app-engine-flex sample:

phpunit.xml is modified to use `test/bootstrap.php` instead of `app/autoload.php`

Is this required for integrating our Sf3 apps to Google app engine flexible, or it is required for internal testing purposes?

If it is required, what is the following files called in that `bootstrap.php`?

```
require_once __DIR__ . '/../../../../testing/ExecuteCommandTrait.php';
require_once __DIR__ . '/../../../../testing/FileUtil.php';
```

**Comment by tmatsuo** [comment]
@lashae 
It's just for internal purpose, so don't worry too much about it.
