### ISSUE TITLE
AppEngineFlexible Symfony ExceptionEventSubscriber

### ISSUE THREAD

**Issue by lashae** [GoogleCloudPlatform/php-docs-samples#571]
I'm trying to figure out the integration of Symfony to Google App Engine Flexible. I don't start a new project, rather I need to deploy my ready app to Google App Engine flexible; so I try to do my best to understand from the sample.

In `config_prod.yml` following recommended configuration ensures that the logs are streamed to StackDriver:

```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:   service
            id:     monolog_psr_batch_logger

services:
    # Monolog wrapper
    monolog_psr_batch_logger:
        class: Monolog\Handler\PsrHandler
        arguments: ['@psr_batch_logger']

    # PsrBatchLogger
    psr_batch_logger:
        class: Google\Cloud\Logging\PsrLogger
        factory: ['Google\Cloud\Logging\LoggingClient', 'psrBatchLogger']
        arguments: ['app']
```

However I couldn't figure out the point for the  [ExceptionSubscriber](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/symfony/src/AppBundle/EventSubscriber/ExceptionSubscriber.php). Since I don't use `auto_wiring` on my project, I need to understand its purpose and register it if required.

Is it required to enable StackDriver for every environment not only for production or something else?

**Comment by tmatsuo** [comment]
@lashae 

Thanks for trying this out! The purpose of the ExceptionSubscriber is to send uncaught exceptions to Stackdriver Error Reporting so that it will be available on the Error Reporting console.

**Comment by lashae** [comment]
Then, I should register it as a service and tag it with `kernel.event_subscriber` in my `services.yml`. Am I correct?

**Comment by Addvilz** [comment]
I am having the same issue. Why is this file there?

**Comment by bshaffer** [comment]
Yes!! That is correct!
