### ISSUE TITLE
Update timestamp example to match other languages.

### ISSUE THREAD

**Issue by jlara310** [GoogleCloudPlatform/php-docs-samples#575]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/7c995cbb8d5ed685d0fdc18264afc31dda3ed84f/firestore/src/update_server_timestamp.php#L46-L49

Can we update to match other samples? Other samples create a single timestamp field. This sample creates the timestamp in an array.

`$docRef->update([ 'timestamp' => FieldValue::serverTimestamp()]);`

**Comment by bshaffer** [comment]
Seems reasonable, I don't know why this sample was done this way.

**Comment by bshaffer** [comment]
This just in from @jdpedrie - the `set` method takes a field/value combo, but the `update` method takes an array of "path" and "value". So this sample is correct.
