### ISSUE TITLE
Uncaught Google\Cloud\Core\Exception\ServiceException: Client error: `POST

### ISSUE THREAD

**Issue by rezapiryghadim** [GoogleCloudPlatform/php-docs-samples#591]
hi 
iam trying to run `quickstart.php` of google translate api but i get this Error anyway : 
also i set project_id inside `quickstart.php.`

Fatal error: Uncaught Google\Cloud\Core\Exception\ServiceException: Client error: `POST https://translation.googleapis.com/language/translate/v2` resulted in a `403 Forbidden` response: <!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport content="initial-scale=1, minimum-scale=1, w (truncated...) in C:\dev\workspace\web\abra\vendor\google\cloud-core\RequestWrapper.php:263 Stack trace: #0 C:\dev\workspace\web\abra\vendor\google\cloud-core\RequestWrapper.php(168): Google\Cloud\Core\RequestWrapper->convertToGoogleException(Object(GuzzleHttp\Exception\ClientException)) #1 C:\dev\workspace\web\abra\vendor\google\cloud-core\RestTrait.php(95): Google\Cloud\Core\RequestWrapper->send(Object(GuzzleHttp\Psr7\Request), Array) #2 C:\dev\workspace\web\abra\vendor\google\cloud-translate\Connection\Rest.php(78): Google\Cloud\Translate\Connection\Rest->send('translations', 'translate', Array) #3 C:\dev\workspace\web\abra\vendor\google\cloud-translate\TranslateClient.php(244): Google\Cloud\Translate\Connection\Rest in C:\dev\workspace\web\abra\vendor\google\cloud-core\RequestWrapper.php on line 263

anyone know what is my problem ?

**Comment by bshaffer** [comment]
You need to replace the placeholder `YOUR_PROJECT_ID` with your actual project ID:

```php
# Your Google Cloud Platform project ID
$projectId = 'YOUR_PROJECT_ID';
```
