### ISSUE TITLE
Error exporting nested data even when setting format to NEWLINE_DELIMITED_JSON

### ISSUE THREAD

**Issue by zgott** [GoogleCloudPlatform/php-docs-samples#601]
I get the below error when trying to export Google Analytics data.
"Error running job: Operation cannot be performed on a nested schema. Field: totals"  The schema is [here](https://support.google.com/analytics/answer/3437719?hl=en) and you can see the "totals" field contains nested data.    I tried to set the format to json, JSON, newline_delimited_json, NEWLINE_DELIMITED_JSON and nothing works.  It seem to think its exporting in CSV.

**Comment by bshaffer** [comment]
hello, can you post your request JSON? There may be an issue with how it's formatted.

**Comment by zgott** [comment]
I'm not constructing the JSON myself.  I'm using the example function extract_table() from https://cloud.google.com/bigquery/docs/exporting-data which uses the class Google\Cloud\BigQuery\BigQueryClient.

The data I'm trying to extract is raw Google Analytics from their BigQuery export feature.  

I've verified that all the variables ($projectId, $datasetId, $tableId etc...) are correct.  I've tried the following values for $format and all return the same error.  

- JSON
- json
- NEWLINE_DELIMITED_JSON
- newline_delimited_json

It seems as if the format param is being ignored.

**Comment by meredithslota** [comment]
@zgott Are you still seeing this issue? There is a newer version of the library, and I am wondering if the issue have been fixed already but we did not follow up here. Let me know?

**Comment by zgott** [comment]
@meredithslota 

We ended up working around this by exporting from BigQuery directly to Cloud DataStore then exporting from there as JSON.

**Comment by meredithslota** [comment]
Ok, thanks for the reply! Glad you found a way. :)

**Comment by cverluise** [comment]
Hello, 
it seems that the issue is still there in `google-cloud-bigquery ="^1.24.0"`
Any fix (except for the manual work around)?
Thanks in advance, 
Cyril

**Comment by lalithkumarpallet** [comment]
Is there a way to upload it as csv, handling the nested schema
