### ISSUE TITLE
Flex: Read/Write/Execute permissions for plugins

### ISSUE THREAD

**Issue by millman2394** [GoogleCloudPlatform/php-docs-samples#615]
We are trying to see if Google App Engine will be a good fit for our Wordpress Sites. I just ran into an issue with a plugin that needs to have a folder with read/write/execute permissions.

"All in One WP Migration is not able to create /app/wordpress/wp-content/plugins/all-in-one-wp-migration/storage folder. You will need to create this folder and grant it read/write/execute permissions (0777) for the All in One WP Migration plugin to function properly."

I noticed in order to upload media files, you need to activate the Google Cloud Storage plugin. So this takes care of that issue, but how should I handle plugins and other I/O?

I thought using Flex instead of Standard would fix this. 

App.yaml

    runtime: php
    env: flex
    
    beta_settings:
      cloud_sql_instances: my-project:us-east4:test-instance
    
    runtime_config:
      document_root: wordpress
    
    env_variables:
      WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname

php.ini

    extension=bcmath.so
    extension=gd.so
    zend_extension=opcache.so
    short_open_tag=On
    google_app_engine.disable_readonly_filesystem = 1

**Comment by bshaffer** [comment]
Unfortunately, even Flex has a read-only filesystem (with the exception of the `/tmp` directory). We don't currently have an out-of-the-box solution to install new plugins in a production App Engine environment. Something like [FileStore](https://cloud.google.com/filestore/) may work.
