### ISSUE TITLE
Unable do install Wordpress on App Engine Standard

### ISSUE THREAD

**Issue by dianaarnos** [GoogleCloudPlatform/php-docs-samples#618]
When running the Wordpress install after deployment, I'm unable to finish the process because the script exceeds the maximum execution time when going from step 1 to step 2 (`wp-admin/install.php?step=2`)
This error only happens on GAE Standard and we are unable to change the default value for `max_execution_ time` of php, so this option shouldn't be available when running `php wordpress-helper.php setup` nor presented as an option on the README.md of `appengine/wordpres`

This is the error registered on Stackdriver:
```
PHP Fatal error: The request was aborted because it exceeded the maximum execution time. in /base/alloc/tmpfs/dynamic_runtimes/php55_dynamic/604979b5e0b1a912/sdk/google/appengine/api/log/LogService.php on line 411
```

**Comment by CarlosKhazs** [comment]
I'm getting a redirect loop (302 error on the GET request on the instance logs) when I try to access the home page. Since I've deployed my application I cannot even access the Wordpress installation page. Actually, none page. I'm using **php72** Standard App Engine.
Any solution?

**Comment by tkhduracell** [comment]
I'm also trying the `appengine/php72/wordpress` sample without any success. Redirect loops when trying to access wp-admin and the `wp cli` command in the README is outdated.

**Comment by bshaffer** [comment]
Hi guys, please try with the new tool and see if the issue persists. I believe it has to do with [this fix](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/wordpress/files/gae-app.php#L40), the App Engine server does not set the `HTTPS` parameter, which WordPress relies on to determine if it's secure, and redirects if it isn't there.

**Comment by bshaffer** [comment]
The fix is as follows:

```php
$_SERVER['HTTPS'] = $_SERVER['HTTP_X_APPENGINE_HTTPS'];
```

**Comment by CarlosKhazs** [comment]
Worked?! @tkhduracell @dianaarnos

**Comment by bshaffer** [comment]
Yay! Thank you! Please open a new issue if you run into anything else!
