### ISSUE TITLE
Firestore Connection in AppEngine

### ISSUE THREAD

**Issue by Meistercoach83** [GoogleCloudPlatform/php-docs-samples#620]
Hi! I´d like to save data to my firestore db from a script that is running in the app engine. 
But all I can see is a page running into a timeout.. isn´t that possible?

**Comment by bshaffer** [comment]
It is possible! You can follow [this example](https://github.com/GoogleCloudPlatform/getting-started-php/blob/restructures-bookshelf-lumen/routes/web.php#L34) and use the [Firestore Client library](http://googleapis.github.io/google-cloud-php/#/docs/google-cloud/latest/firestore/readme)
