### ISSUE TITLE
Unable to access DialogFlow's QueryResult->Parameters

### ISSUE THREAD

**Issue by nicolabeghin** [GoogleCloudPlatform/php-docs-samples#621]
Hi everyone
maybe it's a silly question, but I'm unable to access the content of `QueryResult->Parameters`

I'm using the provided source code, at line
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/dialogflow/src/detect_intent_texts.php#L50

```
$queryResult = $response->getQueryResult();
$parameters=$queryResult->getParameters();
foreach($parameters as $k => $param) {
    print('Something');
}
```

`Something` is never printed out.

I'm running the same query through Postman in order to be sure I actually get something:
![image](https://user-images.githubusercontent.com/2743637/40992679-c329b3ba-68f7-11e8-8a86-899971d77910.png)

I also used `$parameters->serializeToString()` in order to double-check the value _is_ there:
![image](https://user-images.githubusercontent.com/2743637/40992987-9662bf7e-68f8-11e8-8b50-b65ee67a0ecb.png)

thanks
nicola

**Comment by nicolabeghin** [comment]
BTW, a quick/dirty/dumb workaround to get the values out:

`$parameters=json_decode($queryResult->getParameters()->serializeToJsonString(), true);`

**Comment by nnegrey** [comment]
Might be PHP doesn't think this protobuf struct type is a iterable object?
Since QueryResult has a Struct Object: https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.QueryResult

Which links to this: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Struct

I'm not a PHP person, but can try to help pin down Dialogflow issues.

**Comment by nnegrey** [comment]
Closing, but please feel free to comment or re-open if you still need help.

**Comment by fendis0709** [comment]
Maybe it's late to join party, but I found some better workaround code.
You should use method `getFields()` to extract data.

```
$params = [];
if($response->getQueryResult()->getParameters()->getFields()->count()){
    foreach($response->getQueryResult()->getParameters()->getFields() as $key => $value){
        $params[$key] = $value->serializeToJsonString();
    }
}
```

With this code, you get value from parameters Dialogflow Intent in `$params` variable.
```
>>> print_r($params)
Array
(
    [date-time] => "2020-10-02T12:00:00+07:00"
)
```

Read more at docs : 
- http://googleapis.github.io/google-cloud-php/#/docs/cloud-dialogflow/v0.17.0/dialogflow/v2/detectintentresponse
