### ISSUE TITLE
WordPress on Flexible environment - how to get emails working?

### ISSUE THREAD

**Issue by meera** [GoogleCloudPlatform/php-docs-samples#634]
I got wordpress installation working on Google Flex environment.

How does one get emails to work? (Such as form submission notification, comment notification etc).

Since Google Flex environment doesn't support email functionality natively -do we need to install a separate plugin?

**Comment by bshaffer** [comment]
While I don't have a how-to guide here (and I agree we should have one!) we outline how to integrate email services w/ an App Engine Flex application [here](https://cloud.google.com/appengine/docs/flexible/php/sending-emails-with-mailgun)

**Comment by bshaffer** [comment]
Additionally there is a [Mailgun Wordpress Plugin](https://wordpress.org/plugins/mailgun/) which should get you the rest of the way.
