### ISSUE TITLE
Upsert instead of update?

### ISSUE THREAD

**Issue by jlara310** [GoogleCloudPlatform/php-docs-samples#671]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/4b6eb2b08c6b1b9619253a42a02de980526c2919/datastore/api/src/functions/concepts.php#L128

Is there a reason the PHP snippet for update uses upsert in a transaction instead of update in the docs?

https://cloud.google.com/datastore/docs/concepts/entities#datastore-datastore-update-php

**Comment by bshaffer** [comment]
Fixed in 40eedd36947fdbebe42a5a3631351a8a5054fa20
