### ISSUE TITLE
[App Engine] Wordpress Standard Environment - Functionality to use CloudSQL 2nd gen

### ISSUE THREAD

**Issue by 1MichaelOHara** [GoogleCloudPlatform/php-docs-samples#68]
When running the WordPress code generation, It does not let you populate the CloudSQL connection name with the region. I have created a fork with a rough implantation of this feature. 

Would there be an interest to add the functionality to choose between using 1st or 2nd generation CloudSQL instance?

Current example behavior:
```
:/cloudsql/{{project_id}}:{{db_instance}}
```

Expected example behavior:
```
:/cloudsql/{{project_id}}:{{db_region}}:{{db_instance}}
```

**Comment by bshaffer** [comment]
@1MichaelOHara Yes! Please submit a PR with your changes and we will definitely look at merging. I think this would be great functionality.
