### ISSUE TITLE
appengine/php72/wordpress sample does not work

### ISSUE THREAD

**Issue by tkhduracell** [GoogleCloudPlatform/php-docs-samples#683]
Hi, I've been trying to deploy WP on GAE for several hours. I'm able to deploy the app by when accessing it I get into a redirect loop at /wp-admin. 

I'm not very WP knowledgeable. Have anyone successfully deployed this sample?

**Comment by liarsing** [comment]
I got the following error after deploy:
Warning: require(/srv/index.php): failed to open stream: No such file or directory in /srv/gae-app.php on line 41 Fatal error: require(): Failed opening required '/srv/index.php' (include_path='.:/usr/lib/php') in /srv/gae-app.php on line 41

any idea?

**Comment by liarsing** [comment]
Looks like wordpress is not moved to the right place from the log:

Downloading the WordPress archive...
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /home/.../php72/wordpress/vendor/google/cloud-tools/src/Utils/WordPressProject.php on line 161
PHP Warning:  rename(/tmp/wordpress,/home/.../php72/wordpress/my-wordpress-project): Invalid cross-device link in /home/.../php72/wordpress/vendor/google/cloud-tools/src/Utils/WordPressProject.php on line 161

**Comment by bshaffer** [comment]
@tkhduracell this happened to me when I didn't add the `app.yaml` from `files/app.yaml`. Can you confirm you have an `app.yaml` that looks like the one [here](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/wordpress/files/app.yaml)?

@liarsing This is from the command which downloads wordpress to a temporary directory and then moves it into the project directory. Is it possible your temporary directory (e.g. `sys_get_temp_dir`) is actually mounted from another device?

**Comment by liarsing** [comment]
@bshaffer I used cloud shell to do this and the /tmp is pre-configured. After I changed the sys_get_temp_dir to another directory, wordpress deployed successfully.

**Comment by bshaffer** [comment]
I also just updated the WordPress README to be more readable, so hopefully this will also help

**Comment by bshaffer** [comment]
@tkhduracell I think the issue was also with a bug where App Engine Standard does not set the `HTTPS` server variable, which WordPress depends on. Without this, WordPress redirects to `https`, which causes an infinite loop. The fix is to do the following, which has been added to the [WordPress sample front controller](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/wordpress/files/gae-app.php#L40):

```php

$_SERVER['HTTPS'] = $_SERVER['HTTP_X_APPENGINE_HTTPS'];
```

I'm closing this because I believe it's fixed, but _please_ open a new issue if the problem persists!
