### ISSUE TITLE
Readme says use GCS for uploading media, but that plugin doesnt work for php 7.2

### ISSUE THREAD

**Issue by l0c0luke** [GoogleCloudPlatform/php-docs-samples#693]
Shows an error at the top of the page having to do with Guzzle.

**Comment by bshaffer** [comment]
Yes, I've noticed this! 
The plugin DOES work, it just prints a warning at the top.

However, we will try to fix this as soon as possible.

**Comment by bshaffer** [comment]
I found a workaround - go into the plugin directory and run `composer update`:

```
cd /path/to/your/wordpress-project
cd wp-content/plugins/gcs
composer update
cd -
gcloud app deploy
```

This should get rid of the error!
