### ISSUE TITLE
WordPress on App Engine Standard for PHP 7.2 can't continue the installation step

### ISSUE THREAD

**Issue by datar-ai** [GoogleCloudPlatform/php-docs-samples#695]
Hello,

I follow the step on [https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/wordpress](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/wordpress)
After **#gcloud app deploy app.yaml cron.yaml**

Then access the site, and try to continue the installation step, it shows the error message as below:

`Warning: require(/srv/wp-admin/index.php): failed to open stream: No such file or directory in /srv/gae-app.php on line 53 Fatal error: require(): Failed opening required '/srv/wp-admin/index.php' (include_path='.:/usr/lib/php') in /srv/gae-app.php on line 53`

Please advise, thanks.

**Comment by bshaffer** [comment]
Interesting, for some reason `wp-admin/index.php` is not present, but it absolutely should be. Something went wrong in the installation process. What files *are* in your project directory?

I wonder if when WordPress was downloaded and unzipped, it failed to copy the files.

**Comment by datar-ai** [comment]
/php-docs-samples/appengine/php72/wordpress$ ls -la
total 132
drwxr-xr-x  6 roger roger  4096 Aug 30 00:58 .
drwxr-xr-x 16 roger roger  4096 Aug 30 00:56 ..
-rw-r--r--  1 roger roger   253 Aug 30 00:56 composer.json
-rw-r--r--  1 roger roger 78417 Aug 30 00:56 composer.lock
drwxr-x---  3 roger roger  4096 Aug 30 01:43 datar-wordpress-www
drwxr-xr-x  2 roger roger  4096 Aug 30 00:56 files
-rw-r--r--  1 roger roger    21 Aug 30 00:56 .gitignore
-rw-r--r--  1 roger roger   917 Aug 30 00:56 phpunit.xml.dist
-rw-r--r--  1 roger roger  7236 Aug 30 00:56 README.md
drwxr-xr-x  2 roger roger  4096 Aug 30 00:56 test
drwxr-xr-x 17 roger roger  4096 Aug 30 00:56 vendor
-rw-r--r--  1 roger roger  4861 Aug 30 00:56 wordpress.php

/php-docs-samples/appengine/php72/wordpress$ ls -la datar-wordpress-www/
total 40
drwxr-x--- 3 roger roger 4096 Aug 30 01:43 .
drwxr-xr-x 6 roger roger 4096 Aug 30 00:58 ..
-rw-r----- 1 roger roger 1033 Aug 30 00:59 app.yaml
-rw-r----- 1 roger roger   93 Aug 30 00:59 cron.yaml
-rw-r----- 1 roger roger 1667 Aug 30 00:59 gae-app.php
-rw-r----- 1 roger roger  584 Aug 30 00:59 .gcloudignore
-rw-r----- 1 roger roger  295 Aug 30 00:59 php.ini
-rw-r----- 1 roger roger 4605 Aug 30 00:59 wp-config.php
drwxr-xr-x 3 roger roger 4096 Aug 30 00:58 wp-content
roger@datar-www:~/php-docs-samples/appengine/php72/wordpress$

**Comment by bshaffer** [comment]
Looks like `wp-admin` did not make it into your directory. I have no idea why. Try rerunning it and seeing if an error or warning is thrown in the installation process, or just download WordPress manually from `wordpress.org` and unzip it, and then use the following cmmand:

```sh
php wordpress.php update /path/to/unzipped-wordpress-project
```

**Comment by coreysyms** [comment]
I also get this error, I have tried to reinstall with no luck, still get a fatal error. files in my dir are
```app.yaml  cron.yaml  gae-app.php  php.ini  wp-config.php  wp-content```

**Comment by coreysyms** [comment]
> or just download WordPress manually from wordpress.org and unzip it, and then use the following cmmand:

How would one do this via the cloud shell?

**Comment by coreysyms** [comment]
Ok, so after hammering on this. I got wpadmin to load in, however I still get the error

```Warning: require(/srv/index.php): failed to open stream: No such file or directory in /srv/gae-app.php on line 53 Fatal error: require(): Failed opening required '/srv/index.php' (include_path='.:/usr/lib/php') in /srv/gae-app.php on line 53``` I'm thinking this may be a slightly different error, so ill open a new ticket and reference

**Comment by bshaffer** [comment]
Hey @coreysyms! So it's possible this is because the files are failing to copy to your project directory. I've added a branch to this repository that hopefully fixes this problem. Try the following on the command line:

```sh
# CD into where you downloaded this repository
cd /path/to/php-docs-samples
# CD into the wordpress sample directory
cd appengine/php72/wordpress
# checkout the branch where I've added the fix
git checkout fix-wordpress-rename
# pull down the new composer shizzle
composer install
# Now try to run the create command again!
php wordpress.php create
```

Let me know if this works better for you, or if you still get the error!

**Comment by coreysyms** [comment]
@bshaffer Perfect! this runs with no errors now, thanks!

**Comment by bshaffer** [comment]
Yay! Thank you! Please let us know if you experience any other issues!

**Comment by andrzejkrawczyk** [comment]
@bshaffer I have also made from PHP 7.2 in march of 2019 project from docs-samples and https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard by upgrading existing project. I have wp-admin folder in my project. I installed google cloud storage from github repo first but now I want integrate the gae plugin - but I cant activate it.

Warning: require_once(google/appengine/api/urlfetch_service_pb.php): failed to open stream: No such file or directory in /srv/wp-content/plugins/appengine-plugin/modules/urlfetch.php on line 72 Fatal error: require_once(): Failed opening required 'google/appengine/api/urlfetch_service_pb.php' (include_path='.:/usr/lib/php') in /srv/wp-content/plugins/appengine-plugin/modules/urlfetch.php on line 72

Additonally can't run caching plugins on as described.
