### ISSUE TITLE
Where do I have to put the Google Cloud API key?

### ISSUE THREAD

**Issue by JosielFaleiros** [GoogleCloudPlatform/php-docs-samples#704]
I don't know where to put the api key to make the translate [php-docs-samples/translate](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/translate)  work :-/

**Comment by bshaffer** [comment]
Don't use API keys, it is better to use Service Account Credentials. See the README in the link you posted:

2.  **Download The Credentials** - Configure your project using [Application Default Credentials][adc].
    Click "Go to credentials" after enabling the APIs. Click "Create Credentials"
    and select "Service Account Credentials" and download the credentials file. Then set the path to
    this file to the environment variable `GOOGLE_APPLICATION_CREDENTIALS`:
```
    $ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
```
