### ISSUE TITLE
Folder must be writable, but gae is read-only?

### ISSUE THREAD

**Issue by cjcox17** [GoogleCloudPlatform/php-docs-samples#716]
This is a continuation of #706 

The /srv/bootstrap/cache directory must be present and writable.

Env

PHP 7.2
Standard Env
Laravel 5.7

It seems that the function is_writable is called on the $manifestPath, which is set during the app startup process and isn't affected when you change the storagePath via the $app->useStoragePath() function. 
I haven't found a way to forcefully change the manifest path without forking the entire laravel repo, hard coding the manifest path, and changing the composer.json to my repo.

Since the filesystem is readonly, and boostrap/cache must be writable and it is un-changeable. I've looked at the install documentation and the Git Repo for laravel, this has been the case since Laravel 5.1.

My question is, how are others getting it to work as described here?
[https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/laravel-framework](url)

**Comment by flashadvocate** [comment]
Using the database cache driver, this ceases to be an issue

**Comment by flashadvocate** [comment]
What error specifically? Check to make sure bootstrap/cache doesn’t have
any lingering files that might be causing issue.

**Comment by Snaver** [comment]
I've managed to get this working, however it requires a few code changes. See the pull request here https://github.com/GoogleCloudPlatform/php-docs-samples/pull/833.

**Comment by bshaffer** [comment]
This problem should be fixed in the current `php72` runtime. If you still encounter issues, please open a new issue with all the details. Thank you!
