### ISSUE TITLE
How To Enable Bucket Logging

### ISSUE THREAD

**Issue by winni4eva** [GoogleCloudPlatform/php-docs-samples#721]
I need to enable logging for a bucket. I cant seem to find any example for this is the code samples
https://github.com/GoogleCloudPlatform/php-docs-samples.

This is the official google documentation on enabling logging for buckets.
https://cloud.google.com/storage/docs/xml-api/put-bucket-logging

NB: In the absence of php code samples for this I would be happy with any example of using the 
google/cloud-storage composer library to make a custom http request.

**Comment by bshaffer** [comment]
It seems like you've specified the bucket you want logs on already in the variable `$myBucket`

**Comment by winni4eva** [comment]
> It seems like you've specified the bucket you want logs on already in the variable `$myBucket`

@bshaffer are you referring to the array key value pair
```
"logBucket" => "my-bucket"
```
