### ISSUE TITLE
Support for automatic punctuation in Cloud Speech

### ISSUE THREAD

**Issue by Wirone** [GoogleCloudPlatform/php-docs-samples#725]
I saw that in [v0.17.0](https://github.com/googleapis/google-cloud-php-speech/compare/v0.16.2...v0.17.0#diff-7486af0e350b817344b1e8197a999333R97) of PHP Cloud Speech client automatic punctuation was added, but in the [`Google\Cloud\Speech\SpeechClient::formatRequest()`](https://github.com/googleapis/google-cloud-php-speech/blob/master/src/SpeechClient.php#L382-L390) option `enableAutomaticPunctuation` is not supported. As far as I understand, it should be there since all other options listed there are present (in underscore format) in `Google\Cloud\Speech\V1\RecognitionConfig`.

This is only result of my research which might be helfpful, but the real issue is we would like to test automatic punctuation, but we can't :) I don't see issues' section in client library hence I create it here, because it's not documented how to use punctuation, so it probably fits here too.

**Comment by bshaffer** [comment]
Hello @Wirone ! [The sample for auto-punctuation is right here!](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/speech/src/transcribe_auto_punctuation.php#L58)!

**Comment by Wirone** [comment]
@bshaffer thanks, but you don't need to shout :wink: 

FYI: We're working on upgrading to Speech Client 0.30 (API v1) and I've tried `$recognitionConfig->setEnableAutomaticPunctuation(true);` but it does not work with my sample audio file (there is no punctuation) for Hungarian language. Does it work for any supported language?
