### ISSUE TITLE
I want api not to translate private names.

### ISSUE THREAD

**Issue by vienle197** [GoogleCloudPlatform/php-docs-samples#726]
I want the api not to translate the proper names. So what do I need to do?
Ex: 
 - text: Rolex Watch
- from: english 
 - to : japanese

**Comment by bshaffer** [comment]
There is nothing supported in the API for this. However, if you translate HTML, using the class "notranslate" should omit translating the text inside them, according to [this post](https://webapps.stackexchange.com/questions/52668/prohibit-the-translation-of-pieces-of-text-in-google-translate). 

Additionally, you can provide your own markers and substitute the text out before sending it to Google translate.
