### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [13]

### ISSUE THREAD

**Issue by rickbeacham** [GoogleCloudPlatform/php-docs-samples#731]
Following the Wordpress setup for Flex. 

Google Cloud SDK 219.0.1
app-engine-python 1.9.76
bq 2.0.34
cloud-datastore-emulator 2.0.2
core 2018.09.28
gsutil 4.34

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.DS_Store$

**Comment by rickbeacham** [comment]
There seems to be a problem with either the Project Ownership or the App Engine instance.

**Comment by bshaffer** [comment]
Were you able to diagnose  the issue? With the information provided I was not able to duplicate the error.

**Comment by bshaffer** [comment]
Error response 13 means "Maximum number of versions reached". This means you need to delete some versions with `gcloud app versions delete` before you can deploy a new version.
