### ISSUE TITLE
force HTTPS on drupal 8

### ISSUE THREAD

**Issue by cesardmoro** [GoogleCloudPlatform/php-docs-samples#734]
any idea about how to force https on drupal 8  ?

this wont work 
header(" Strict-Transport-Security: max-age=31536000; includeSubDomains; preload");

added ngix.app.yml file and broke my site.

**Comment by grayside** [comment]
Hi cesardmoro, where are you trying to host your Drupal site? Is this on App Engine PHP 7.2? Somewhere else?

**Comment by bshaffer** [comment]
If you are using App Engine Flex, take a look at [this page](https://cloud.google.com/appengine/docs/flexible/php/application-security). If you are using App Engine standard, take a look at [this page](https://cloud.google.com/appengine/docs/standard/php7/application-security)
