### ISSUE TITLE
Problem downloading files from bucket

### ISSUE THREAD

**Issue by wickywills** [GoogleCloudPlatform/php-docs-samples#737]
I can upload files to my bucket just fine using something like:

`php storage/storage.php objects --upload-from=. [BUCKET_NAME] [MY_FILE]`

However I am now trying to download a file from my bucket using:

`php storage/storage.php objects [BUCKET_NAME] [MY_FILE] --download-to="[MY_PATH]"`

But I receive the following message

> Warning: fopen(.): failed to open stream: Is a directory in /storage/vendor/google/cloud-storage/src/StorageObject.php on line 598

So I guessed that the --download-to option should be a file and not a directory? I tried pointing it to a new file instead, and when I run the command I receive the following, implying that the download was successfull:

> Downloaded gs://[MY FILE] to [MY_FILE]

However when I check [MY_FILE], it is just an empty file of 0 bytes. 

Is this a problem with the samples provided, or am I using the script incorrectly?

**Comment by bshaffer** [comment]
Hello @wickywills !

If you want to manage your files, use `gsutil` which is bundled with the [Google Cloud SDK](https://cloud.google.com/sdk). 

As for your issue, I was not able to duplicate it. The following worked for me:

```sh
 php storage.php objects [BUCKET] [OBJECT] --download-to=[OBJECT]
```
