### ISSUE TITLE
No Clear documentation For installing on server

### ISSUE THREAD

**Issue by irfan900** [GoogleCloudPlatform/php-docs-samples#747]
i am stuck into this https://github.com/GoogleCloudPlatform/php-docs-samples … .in the source codes its just using project id to make connection with database no service key etc .   add_data('your-project-id'); but when i call that function it gives error

**Comment by kunalrawat425** [comment]
Yes i Agree, connecting with projectId is not sufficient,you need to authorize your self with service key as json file,which makes connection live,below is method you can connect hope it helps
    public function config(){
        $projectId = 'clean-fin-818';
        $keyFilePath = ROOT.'/vendor/firestore/vendor/group-chat-service.json';
            $db = new FirestoreClient([
                'projectId' => $projectId,
                'keyFilePath' => $keyFilePath
            ]);
        return $db;
    }

**Comment by irfan900** [comment]
thanks sir i was missing about giving path
