### ISSUE TITLE
How Laravel example works ?

### ISSUE THREAD

**Issue by taliptako** [GoogleCloudPlatform/php-docs-samples#751]
I tried with Laravel 5.6 and 5.7 in both I'm getting the same issue php artisan package:discover command does not work because there is a php class which calls /bootstrap/cache it doesn't listen to method below
`$app->useStoragePath(env('APP_STORAGE', base_path() . '/storage'));`
I can't understand how you guys make it work?

**Comment by nucreativa** [comment]
add this line ` APP_STORAGE: /tmp` on your `app.yaml` so it will be look like this
```
runtime: php72
env_variables:
  # Put production environment variables here.
  APP_STORAGE: /tmp
```

**Comment by taliptako** [comment]
> add this line ` APP_STORAGE: /tmp` on your `app.yaml` so it will be look like this
> 
> ```
> runtime: php72
> env_variables:
>   # Put production environment variables here.
>   APP_STORAGE: /tmp
> ```

I already tried it. It doesn't work.

**Comment by bshaffer** [comment]
Is this error happening locally or in production or during deployment? Can you provide us with a full stack trace?

**Comment by taliptako** [comment]
> Is this error happening locally or in production or during deployment? Can you provide us with a full stack trace?

It happens in production during deployment. If you look at the composer.json of laravel in the post-autoload-dump script it runs php artisan package:discover command which writes files inside bootstrap/cache and in laravel its static which you cant change. You can see here [](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/ProviderRepository.php)
I was deploying with git and Cloud Build and i didnt add those files to git so i get error it tried to write something because ..
But when i add them to git it runs but i dont know if its good to add those files to git..

**Comment by bshaffer** [comment]
Have you tried removing the `post-autoload-dump` script from `composer.json`?

**Comment by taliptako** [comment]
> Have you tried removing the `post-autoload-dump` script from `composer.json`?

Who will discover my packages then :)

**Comment by taliptako** [comment]
I'm already make it work by adding those files to git. From google side i would like to have writing permission during deployment. Otherwise its something Laravel can fix by making /bootstrap/cache dynamically changeable..

**Comment by bshaffer** [comment]
`/tmp` is already writable. I think we can get Laravel to write to it, you probably just need to manually inject `APP_STORAGE` into `composer.json`, like follows:

```
   "APP_STORAGE=/tmp php artisan package:discover"
```

Adding write permissions to arbitrary directories won't happen in App Engine, but we should definitely be able to track this issue down and fix it on the Laravel side if necessary!

**Comment by taliptako** [comment]
> > Is this error happening locally or in production or during deployment? Can you provide us with a full stack trace?
> 
> It happens in production during deployment. If you look at the composer.json of laravel in the post-autoload-dump script it runs php artisan package:discover command which writes files inside bootstrap/cache and in laravel its static which you cant change. You can see here 
> I was deploying with git and Cloud Build and i didnt add those files to git so i get error it tried to write something because ..
> But when i add them to git it runs but i dont know if its good to add those files to git..

Sorry i forget adding link here [https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/ProviderRepository.php](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/ProviderRepository.php)

**Comment by Snaver** [comment]
I've managed to get this working, however it requires a few code changes. See the pull request here https://github.com/GoogleCloudPlatform/php-docs-samples/pull/833.
