### ISSUE TITLE
How to detect entities in training phrase by api?

### ISSUE THREAD

**Issue by moris8704** [GoogleCloudPlatform/php-docs-samples#759]
Hi, I'm trying to implement dialogflow by php.
I have tried the functions on web console, it works.
Then I tried to do the same things by php, I can update intent with training phrase, but the entities would not detect.
Dose it mean that I have to build Part and then set it into TrainingPhrase ?
Or there exists function that can be used to update intent and detect entities?

**Comment by nnegrey** [comment]
Hi, are you having a problem with a specific sample not working?

**Comment by moris8704** [comment]
I think they work fine.
Just want to know that is there a way to add Training phrases and then detect entities automatically.
But we directly did that on web console.

**Comment by nnegrey** [comment]
How soon after updating are you trying to call a `detectIntentRequest`?
There is some delay between an update and when the Agent has "trained" on the new data.

**Comment by moris8704** [comment]
Well, I just checked on web console after add phrase.
Maybe I will try it next time. Hope it works. Our project should need it.
Thanks for your reply.

**Comment by nnegrey** [comment]
Happy to help, let me know if there's anything more I can dig into.
