### ISSUE TITLE
Different results of query by Kind and query by GQL 

### ISSUE THREAD

**Issue by laocoi** [GoogleCloudPlatform/php-docs-samples#778]
I have 2 types of query, by Kind and by GQL
```
$query = $datastore->query()->kind('files')->filter('tags','=','texture')->filter('tags','=','newspaper')->start($pageCursor);
This gives more results than bellow query:

$query = $datastore->gqlQuery("SELECT * FROM files where tags='texture' and tags='newspaper'",['allowLiterals' => true]);
```
Why their results are not the same?

**Comment by bshaffer** [comment]
This error is better fit for the https://github.com/googlecloudplatform/google-cloud-php repository. The issues in repository are strictly for the sample code.

**Comment by dwsupplee** [comment]
Thanks for the report @laocoi, we are looking in to this. Please follow https://github.com/googleapis/google-cloud-php/issues/1696 for further updates :).
