### ISSUE TITLE
WordPress REST API query params not working properly on GAE Standard PHP7.2

### ISSUE THREAD

**Issue by ptsteadman** [GoogleCloudPlatform/php-docs-samples#809]
After following the instructions [here](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/wordpress) for setting up a new WordPress installation on GAE standard 7.2, query params used for filtering content via the wp-json rest API included in WordPress do not behave as expected. 

Example 404 request of WordPress deployed on GAE: https://stock-dot-wordpress-test-222422.appspot.com/wp-json/wp/v2/pages?slug=sample-page

Expected behavior: http://demo.wp-api.org/wp-json/wp/v2/pages?slug=sample-page

Non-query param requests work fine: https://stock-dot-wordpress-test-222422.appspot.com/wp-json/wp/v2/pages

This issue seems to be the result of a change in how the GAE PHP 7.2 standard environment serves requests, as the `/pages?slug=` requests were working fine up until around December 22nd 2018, and redeploying WordPress to the GAE flex environment fixes the issue. Past known good service versions do not work. (You can read more about the details of our headless setup [here](https://computerlab.io/2018/12/20/deploying-headless-wordpress-on-gcp/) if it's helpful.)

It would be very helpful to know if this is a bug in GAE PHP 7.2 standard environment, or an intentional change. It'd also be helpful to know if there's a workaround / way to configure the service so that the wp-json API can be used on the standard environment.

**Comment by ptsteadman** [comment]
I added an issue in the issue tracker as well as this might not be an issue with the code in this resource but rather the platform: https://issuetracker.google.com/issues/122553575

**Comment by bshaffer** [comment]
Closing, as the corresponding issue was closed (due to lack of response)
