### ISSUE TITLE
List all Training Phrases per intent

### ISSUE THREAD

**Issue by basiteaal** [GoogleCloudPlatform/php-docs-samples#832]
Hi all,

I do have the following working code in my PHP application to list all my intents (pretty much example from the SRC). I do miss one thing which I not get to work fine; get a list of all training phrases per intent.

Can anyone help me out?

PS. I tried a for each on $intent->getTrainingPhrases(); which gives me a Protobuf object; but it's not possible to set a foreach on that one.

```
    $intentsClient = new IntentsClient([
      'credentials' => './dialogflowAuthentication/xxx.json'
    ]);
    $parent = $intentsClient->projectAgentName($projectId);
    $intents = $intentsClient->listIntents($parent);
    
    foreach ($intents->iterateAllElements() as $intent) {
        // print relevant info
        print(str_repeat("=", 20) . PHP_EOL);
        printf('Intent name: %s' . PHP_EOL, $intent->getName());
        printf('Intent display name: %s' . PHP_EOL, $intent->getDisplayName());
        printf('Action: %s' . PHP_EOL, $intent->getAction());
        printf('Root followup intent: %s' . PHP_EOL,
            $intent->getRootFollowupIntentName());
        printf('Parent followup intent: %s' . PHP_EOL,
            $intent->getParentFollowupIntentName());
        print(PHP_EOL);
        print('Input contexts: ' . PHP_EOL);
        foreach ($intent->getInputContextNames() as $inputContextName) {
            printf("\t Name: %s" . PHP_EOL, $inputContextName);
        }
        print('Output contexts: ' . PHP_EOL);
        foreach ($intent->getOutputContexts() as $outputContext) {
            printf("\t Name: %s" . PHP_EOL, $outputContext->getName());
        }
        printf($intent->getTrainingPhrases->getParts());
    }
    $intentsClient->close();
```

**Comment by jdpedrie** [comment]
To retrieve the training phrases along with intents, you need to set the `intentView` option:

```php
use Google\Cloud\Dialogflow\V2\IntentView;

$intents = $this->intents->listIntents($parent, [
    'intentView' => IntentView::INTENT_VIEW_FULL
]);
```

Once you do this, `$intent->getTrainingPhrases()` will return an instance of `Google\Protobuf\Internal\RepeatedField`, which should be interable (i.e. you can `foreach` it).

**Comment by basiteaal** [comment]
Awesome; added the intentView option and added following lines of code.

```
        foreach ($intent->getTrainingPhrases() as $trainingPhrase) {
          foreach ($trainingPhrase->getParts() as $trainingPhrasePart){
            printf("\t Phrase: %s" . PHP_EOL, $trainingPhrasePart->getText());
          }
        }
```

Seems to do the trick.

Would be a good idea in my opinion to add this to this example code:
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/dialogflow/src/intent_list.php

**Comment by bharatsewani1993** [comment]
Hi,
How can I list all the Messages of an intent?
I mean all the answers which an intent have? How can I list those?
.
Thanks in Advance?
