### ISSUE TITLE
Files/directories listed in .gcloudignore are still uploaded

### ISSUE THREAD

**Issue by gmdev** [GoogleCloudPlatform/php-docs-samples#845]
I'm deploying a Symfony app to PHP 7.2 App Engine Standard environment.

I have a `.gcloudignore` file at the root directory of the project with the following content:

```
 .gcloudignore
 .git
 .gitignore
 /.env
 /.env.*
 #!include:.gitignore
```

and `.gitignore`:
```
.DS_Store
/.idea/

###> symfony/framework-bundle ###
/.env.local
/.env.local.php
/.env.*.local
/public/bundles/
/var/
/vendor/
###< symfony/framework-bundle ###

###> symfony/phpunit-bridge ###
.phpunit
/phpunit.xml
###< symfony/phpunit-bridge ###

###> symfony/web-server-bundle ###
/.web-server-pid
###< symfony/web-server-bundle ###
```

My problem is that all those files listed in the ignore files are still uploaded regardless. Effectively I have to manually delete `/vendor` and `/var` directories before deployment, otherwise it exceeds the 10,000 files limit and fails. My development `.env` file is also uploaded which prevents proper deployment.

I'm on MacOS Mojave and using `Google Cloud SDK 235.0.0`. The command I'm using to deploy is:

```
gcloud app deploy app.stage.yaml --project=MY_PROJECT
```

On `beta` channel it doesn't work neither:

```
gcloud beta app deploy app.stage.yaml --project=MY_PROJECT
```

After adding ` --verbosity=debug` I can actually see the `.gloudignore` file is found and supposedly "used", but in fact it isn't:

```
Beginning deployment of service [default]...
INFO: Using .gcloudignore file at [PATH_TO_MY_PROJECT/.gcloudignore].
DEBUG: Skipping upload of [config/bundles.php]
DEBUG: Skipping upload of [config/packages/dev/routing.yaml]
DEBUG: Skipping upload of [config/packages/dev/debug.yaml]
(...)
DEBUG: Skipping upload of [.gitignore]
DEBUG: Skipping upload of [.git/refs/remotes/origin/HEAD]
(...)
```

From what I see, "skipping upload of XXX"  actually means that the file has already been uploaded, therefore it won't be uploaded again. It doesn't mean that it has been recognized as ignored.

What's is going on here?

**Comment by dpkirchner** [comment]
@gmdev What was the resolution of this issue?

**Comment by HaipengSu** [comment]
Hi, @gmdev, did you figure it out? I have the same issue here, and .gcloudignore is not ignoring the filges/folders for deployment.

**Comment by thdk** [comment]
I have found the solution for this problem...

Remove the leading spaces in your `.gcloudignore` file and your problem will be solved! 

I had the exact same issue because I copied the content for the `.gcloudignore` file from their documentation page.

So instead of:

```
  .gcloudignore
  .git
  .gitignore
  /.env
  /.env.*
  #!include:.gitignore
```

You should have:

```
.gcloudignore
.git
.gitignore
/.env
/.env.*
#!include:.gitignore
```

**Comment by gmdev** [comment]
Yes, in my case it was the extra space at the beginning of each line too (as you can see in my first post) :)

Should have mentioned that for other people looking for solution to the same issue.

**Comment by HaipengSu** [comment]
Thanks the reply. @thdk, @gmdev. In my case, somehow my .gcloudignore was disabled. After reebling .gcloudignore by running `gcloud config set gcloudignore/enabled true`, the problem was resolved.

**Comment by nicolasassi** [comment]
Also have this problem and nothing seems to solve it. Neither removing whitespaces in the beggining nor running gcloud config set gcloudignore/enabled true

**Comment by Kenan7** [comment]
> Also have this problem and nothing seems to solve it. Neither removing whitespaces in the beggining nor running gcloud config set gcloudignore/enabled true

I also had the problem, is your gcloudignore file in project root directory?

**Comment by cuducos** [comment]
Same issue here.

* `.gcloudignore` in the root directory
* no leading space in the `.gcloudignore` lines
* configured _gcloudignore_ to true in `gcloud`

And still it tries to upload directories listed in `.gcloudignore`:

```
.env
data/
```

And, from the output of `gcloud app deploy` I spot some lines as:

```
copied /home/cuducos/my-project/data/.gitkeep to /tmp/tmpk_29494n/tmp5niqhou8/data/.gitkeep
```

Since `/home/cuducos/my-project/` is the root of the project, and the directory in which `.gcloudignore` is, and since `data/` is on `.gcloudignore`, why is it uploading `data/.gitkeep`?

**Comment by wrunk** [comment]
@cuducos I think that's just the local copying portion of the command which will just copy everything in your project dir regardless of the gcloudignore. The actual uploading process comes later which should respect the gcloudignore (confirm which files were actually uploaded by looking at the manifest at the end of the command - make sure to have --verbosity=info set in your command)

**Comment by cuducos** [comment]
> I think that's just the local copying portion of the command which will just copy everything in your project dir to a tmp dir regardless of the gcloudignore

That's true.

Still a UX problem in my use case: some directory (data and models) in my `.gcloudignore` have Gb of files. COpying this seems unnecessary and just slows down the work flow.

**Comment by Kenan7** [comment]
What is this? I think I am not involved in this topic. Maybe there was a
mistake?

**Comment by wrunk** [comment]
@cuducos yep I agree. Personally im leaning toward doing:
- Creating a tmp dir locally
- rsync only things i want to deploy there
- gcloud app deploy...
- rm tmp dir

**Comment by bshaffer** [comment]
@manoadamro if you think there's a bug, please open a new issue (this one has been closed by the author) and provide all the information so that it can be reproduced. The consensus on this bug seems to be all file are copied, but the ones that are uploaded respect the `.gcloudignore` file.

It should be mentioned that any issue in this file would be an issue in the `gcloud` utility, which would be a problem across all the languages of the platform. As this tool has been around a long time, I think this is not likely to be the case.
