### ISSUE TITLE
Laravel on App Engine Standard

### ISSUE THREAD

**Issue by VelocityCS** [GoogleCloudPlatform/php-docs-samples#852]
I don't seem to be able to get past the error of
**file_put_contents(/tmp/framework/sessions/<randomletters>): failed to open stream: No such file or directory**

**php artisan --version**
_Laravel Framework 5.8.3_

So I have researched this, and read [https://github.com/GoogleCloudPlatform/php-docs-samples/issues/706](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/706)

I have also followed exactly the guide on [https://cloud.google.com/community/tutorials/run-laravel-on-appengine-standard](https://cloud.google.com/community/tutorials/run-laravel-on-appengine-standard)

However, I repeatedly get the issue of:
**file_put_contents(/tmp/framework/sessions/<randomfilename>): failed to open stream: No such file or directory**

The two differences I see from the guide are:
1. _"Create a new Laravel project using the laravel installer: laravel new blog"_
Instead I did: 
**composer create-project laravel/laravel --prefer-dist test_laravel_app**

2. _"composer remove --dev beyondcode/laravel-dump-server"_ returns:
_beyondcode/laravel-dump-server is not required in your composer.json and has not been removed
Package "beyondcode/laravel-dump-server" listed for update is not installed. Ignoring._

I have tried using:
**php artisan route:clear
php artisan config:clear
php artisan cache:clear
composer dump-autoload**

**Comment by bshaffer** [comment]
Thanks for filing this! The main issue here is that the directory `/tmp/framework/sessions/` doesn't exist, and laravel is not creating it. In the tutorial we use [database sessions](https://cloud.google.com/community/tutorials/run-laravel-on-appengine-standard#set_up_database_sessions) to get around this issue. Did you try setting those up?

**Comment by VelocityCS** [comment]
Thanks bshaffer, no not yet. In the tutorial it showed at step 6 after **app deploy** that I should be able to see a nude Laravel site, so I didn't move past that stage until I had that working. Will give it a go

**Comment by VelocityCS** [comment]
Okay, I created the new db and ran the migration, but now get a slightly different error:

**SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `sessions` where `id` = randomletters limit 1)**

I used SQL Workbench to confirm that the db and the tables were created successfully: **migrations**, **password_resets**, **sessions** and **users** tables are there.

**migrations** has 3 entries (_create_users_table_, _create_password_resets_table_, and _create_sessions_table_).

The other 3 tables do have the relevant columns but are all empty.

I again tried clearing caches and dump-autoload but still the same error

**Comment by VelocityCS** [comment]
Futher update: In my app.yaml for DB_SOCKET: I'd put the short name instead of the full name:name:name

I did another:
php artisan route:clear
php artisan config:clear
**php artisan cache:clear**

And got the warning:

-----
_Route cache cleared!_
_Configuration cache cleared!_

   _Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravelappengine.cache' doesn't exist (SQL: delete from `cache`)_

  _at C:\Users\me\Documents\DevOps\GCP\App Engine\lara-on-google-for-web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664_
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  _Exception trace:_

  _1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravelappengine.cache' doesn't exist")_
      _C:\Users\me\Documents\DevOps\GCP\App Engine\lara-on-google-for-web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:479_

  _2   PDO::prepare("delete from `cache`")_
      _C:\Users\me\Documents\DevOps\GCP\App Engine\lara-on-google-for-web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:479_

  _Please use the argument -v to see more details._

-----

And then when I **gcloud app browse** I now get:

**(1/1) InvalidArgumentException
Please provide a valid cache path**

**Comment by VelocityCS** [comment]
So being logical, I then tried:
**php artisan cache:table**
**php artisan migrate --force**
_Migrating: 2019_03_08_165712_create_cache_table_
_Migrated:  2019_03_08_165712_create_cache_table_
Again, confirmed that the table was created and fields there (it is) but still the same error. Feels like I'm so close..!

**Comment by VelocityCS** [comment]
Well, after some more research, from this document [https://cloud.google.com/appengine/docs/standard/php7/runtime](https://cloud.google.com/appengine/docs/standard/php7/runtime) I quote:
**Filesystem**
_The runtime includes a writable **/tmp** directory, with all other directories having read-only access._

So I changed my app.yaml to:
**CACHE_DRIVER: /tmp**

I then did another:
**php artisan route:clear**
**php artisan config:clear**
**php artisan cache:clear**
**composer dump-autoload**
**gcloud app deploy**

Still exactly the same error. I did local cachebusting by adding _?foo=3472854_ but still the same

**Comment by VelocityCS** [comment]
Added:
**VIEW_COMPILED_PATH: /tmp**

And now working

**Comment by carlospalacin** [comment]
@VelocityCS What changes have you made to make it work? I have the same problem, thanks!

**Comment by bshaffer** [comment]
If you add `SESSION_DRIVER: cookie` to your `app.yaml` environment variables, you do not need to have database sessions to avoid the initial error.  See https://github.com/GoogleCloudPlatform/php-docs-samples/pull/856:

```yaml
# app.yaml
runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
```

As for your PDO errors, I am still looking into it

**Comment by bshaffer** [comment]
I've updated the tutorial with some of your fixes. I was unable to duplicate the issue with DB sessions. Closing this as fixed, please reopen if you encounter the same issues!

**Comment by infinite-sea** [comment]
Was having some issues with Laravel 6 deployment, and was able to fix based on this feedback : 
https://stackoverflow.com/questions/58087153/laravel-with-app-engine-standard-class-facade-ignition-ignitionserviceprovider

Suggestion : update tutorial  ( Step 5 )with : gcloud beta app deploy --no-cache

**Comment by neysi** [comment]
Error with Laravel 6.

.yaml

```
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
```

```
Step #1 - "builder": In PackageManifest.php line 168:
Step #1 - "builder":                                                                           
Step #1 - "builder":   The /workspace/bootstrap/cache directory must be present and writable.  
```

```
Step #1 - "builder": Writing lock file
Step #1 - "builder": Generating optimized autoload files
Step #1 - "builder": > Illuminate\Foundation\ComposerScripts::postAutoloadDump
Step #1 - "builder": > @php artisan package:discover --ansi
Step #1 - "builder": Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by bshaffer** [comment]
Hi @neysi can you please open up a new issue with this information?

**Comment by dangerdan** [comment]
> Error with Laravel 6.
> 
> .yaml
> 
> ```
>   APP_STORAGE: /tmp
>   VIEW_COMPILED_PATH: /tmp
> ```
> 
> ```
> Step #1 - "builder": In PackageManifest.php line 168:
> Step #1 - "builder":                                                                           
> Step #1 - "builder":   The /workspace/bootstrap/cache directory must be present and writable.  
> ```
> 
> ```
> Step #1 - "builder": Writing lock file
> Step #1 - "builder": Generating optimized autoload files
> Step #1 - "builder": > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> Step #1 - "builder": > @php artisan package:discover --ansi
> Step #1 - "builder": Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> ```

Did you resolve this? Having the same issue, works when I remove "package:discover"

**Comment by Alexuisis** [comment]
same for L7 when usign google cloud build (after cmd composer update)

**Comment by elijah-schow** [comment]
I'm also getting the `The /workspace/bootstrap/cache directory must be present and writable.` error. I'm using GAE and Laravel 6. Removing `@php artisan package:discover --ansi` in`"post-autoload-dump"` from `composer.json` as @dangerdan suggested does not resolve the issue for me.

**Comment by neysi** [comment]
The solution is using this command:
`gcloud beta app deploy --no-cache`
Tested on L6 and L7.

**Comment by LarryBarker** [comment]
This is probably the most helpful App Engine thread for a Laravel app I've found. I'm curious, what is everyone doing for migrations? 

We're currently using cloud proxy and changing env values locally, then running migrations. This drives me crazy, and is extremely risky (especially in a production environment). Imagine forgetting to swtich back or missing one of the env variables, and running migrations or seeds ... while still connected to the production db. 

Surely there has to be a way to run artisan commands as part of the build process? I typically use Forge and Envoyer for deployments, but my current project doesn't favor this setup.

**Comment by tundachef** [comment]
> So being logical, I then tried: **php artisan cache:table** **php artisan migrate --force** _Migrating: 2019_03_08_165712_create_cache_table_ _Migrated: 2019_03_08_165712_create_cache_table_ Again, confirmed that the table was created and fields there (it is) but still the same error. Feels like I'm so close..!

This worked for me
