### ISSUE TITLE
Detect intent from audio

### ISSUE THREAD

**Issue by tgssb** [GoogleCloudPlatform/php-docs-samples#859]
What is the limit of seconds for the detection of intention by audio ?
I'm using ogg files, and **it only detects audios for a maximum of 5 seconds**.

```
$inputAudio = file_get_contents("/home/testfile.ogg");

$audioConfig = new InputAudioConfig();
$audioConfig->setAudioEncoding(AudioEncoding::AUDIO_ENCODING_OGG_OPUS);
$audioConfig->setLanguageCode($languageCode);
$audioConfig->setSampleRateHertz(16000);

$queryInput = new QueryInput();
$queryInput->setAudioConfig($audioConfig);


$response = $sessionsClient->detectIntent($session, $queryInput, ['inputAudio' => $inputAudio]);
```

**Comment by bshaffer** [comment]
Hi @tgssb !

Have you tried running this using the `StreamingDetectIntentRequest` object? [Here is an example](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/2048a217fd1a3df6b5f632281472340cf8aee444/dialogflow/src/detect_intent_stream.php#L56)
