### ISSUE TITLE
Remove/Update PHP Unit

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/php-docs-samples#860]
In https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/flexible/wordpress/composer.json Please update since the following image shows up. 

<img width="1465" alt="Screen Shot 2019-03-22 at 9 00 30 PM" src="https://user-images.githubusercontent.com/4000076/54859725-33b27300-4ce7-11e9-90e4-14d2f034f854.png">

**Comment by bshaffer** [comment]
We were previously supporting PHPUnit 5 because our code samples were running on PHP 5.6. Now that this has been updated to only support PHP 7.1 and above, we can upgrade PHPUnit.

**Comment by bshaffer** [comment]
Fixed by https://github.com/GoogleCloudPlatform/php-docs-samples/pull/918
