### ISSUE TITLE
Not working from browser

### ISSUE THREAD

**Issue by bhavyeshdhaduk** [GoogleCloudPlatform/php-docs-samples#862]
I am using Google cloud speech-to-text API and setup project in localhost and live with credential and environment variable. It working with only command line while I run it through browser it gives me below error
`
Fatal error: Uncaught DomainException: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information in /jet/app/www/default/speech/vendor/google/auth/src/ApplicationDefaultCredentials.php:156 Stack trace: #0 /jet/app/www/default/speech/vendor/google/gax/src/CredentialsWrapper.php(197): Google\Auth\ApplicationDefaultCredentials::getCredentials(Array, Object(Google\Auth\HttpHandler\Guzzle6HttpHandler), NULL, NULL) #1 /jet/app/www/default/speech/vendor/google/gax/src/CredentialsWrapper.php(114): Google\ApiCore\CredentialsWrapper::buildApplicationDefaultCredentials(Array, Object(Google\Auth\HttpHandler\Guzzle6HttpHandler)) #2 /jet/app/www/default/speech/vendor/google/gax/src/GapicClientTrait.php(326): Google\ApiCore\CredentialsWrapper::build(Array) #3 /jet/app/www/default/speech/vendor/google/gax/src/GapicClientTrait.php(308): Google\Cloud\Speech\V1\Gapic\SpeechGapicClient->createCredentialsWrapper(NULL, Array) #4 /jet/app/www/default/speech in /jet/app/www/default/speech/vendor/google/gax/src/CredentialsWrapper.php on line 200`

**Comment by bshaffer** [comment]
This is probably because you've properly set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` in your CLI environment, but not in your browser environment. Try the following (before you make the call):

```php
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-credentials.json');
```

**Comment by Ahsankhan001** [comment]
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-credentials.json');
