### ISSUE TITLE
Tutorial is not official

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/php-docs-samples#883]
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/6ccd02e6ee54d897ca643ec46771c799c7db7c37/appengine/php72/wordpress/README.md says, "Please refer to the official tutorial for running the code in this sample."

First thing on https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard is the "Google Cloud Platform Community tutorials submitted from the community do not represent official Google Cloud Platform product documentation."

Pick one.

**Comment by bshaffer** [comment]
fixed in e25e57a4f3eb00fbb2eeaf5a12198403999c59ee
