### ISSUE TITLE
[PHP/7.2] AppEngine Standard --> Redis Connection

### ISSUE THREAD

**Issue by fschirl** [GoogleCloudPlatform/php-docs-samples#886]
Hi,

currently I'm using AppEngine 7.2 flexible. I do have memorystore / redis enabled in the same project and connection with redis extension is working fine with flexible .

When switching over to standard php 7.2 environment i always get an connection timeout to my redis instance, so i can't connect.
php.ini:
extension=redis.so

php code (example)
`
$RedisHandle = new Redis();
$RedisHandle->connect('10.0.0.3', '6379', 10);
`

10.0.0.3 is the listed IP within Memorystore 

As being said, flexible is working fine, but standard connection is not possible

**Comment by bshaffer** [comment]
Hello @fschirl !
Thank you for filing this issue. Currently the only way to connect to Memorystore from App Engine is via [Serverless VPC Access](https://cloud.google.com/vpc/docs/configure-serverless-vpc-access). I will write up a tutorial for this soon.

**Comment by bshaffer** [comment]
@fschirl please check out the [Memorystore with App Engine PHP 7.2](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/memorystore) sample we just merged, and let me know if you have any questions!
