### ISSUE TITLE
error from running composer

### ISSUE THREAD

**Issue by joshuabrooks** [GoogleCloudPlatform/php-docs-samples#901]
Hi

After installing composer and then trying to run the command as stated in the lab I get the following message. Could you please tell me how I get the composer file with all the dependencies?

~/php-docs-samples/appengine/wordpress (wordpress-lab-242108)$ composer install --no-dev

Composer could not find a composer.json file in /home/jos_brooks/php-docs-samples/appengine/wordpress

To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by bshaffer** [comment]
Hi @Joshuabrooks ! 
The problem is you're in `appengine/wordpress` when you should be in `appengine/flexible/wordpress`.  

This was our fault, looks like the path in the codelab was wrong. It's now been updated. Thank you for reporting this!
