### ISSUE TITLE
[App Engine] Update README prerequisites

### ISSUE THREAD

**Issue by 1MichaelOHara** [GoogleCloudPlatform/php-docs-samples#91]
Memcache and PHP 5.5 should be added as prerequisites or mentioned in the README since they are need for running WordPress Standard Environment locally. 

EDIT: I currently have not looked into documenting the prerequisites for the Flexible Environment.

**Comment by bshaffer** [comment]
Closing this as memcache IS mentioned in the php55 wordpress readme.
