### ISSUE TITLE
PHP 7.2 WebP Support

### ISSUE THREAD

**Issue by taliptako** [GoogleCloudPlatform/php-docs-samples#912]
It would be better if we can have WebP support with GD or Imagick extension.

**Comment by bshaffer** [comment]
I have not tested this out, but this should be included in  the `php72` runtime already (see the [output of phpinfo here](http://php72-ini.appspot.com/))

**Comment by taliptako** [comment]
@bshaffer Sorry I forget add i request this for Standard env runtime not for the flexible engine images 
Is this phpinfo from standard env ? Recently i tried to process webp images in standard env and i get an error that my extension doesn't support webp

**Comment by bshaffer** [comment]
This php.ini is from the standard php72 runtime. 

What extension is necessary for this? If it's GD, it should be compiled already. If it's imagemagick, try adding `extension=imagick` to your `php.ini`.

**Comment by bshaffer** [comment]
After looking into it, the `--with-webp-dir` needs to be compiled in, which is not the case in our PHP configuration. 

I would suggest looking into [Cloud Run](https://cloud.google.com/run/docs/quickstarts/build-and-deploy#php), which allows you to deploy arbitrary containers. In this environment you will be able to compile webp into the runtime, and you'll still have the appengine benefits of autoscaling, scaling down to zero, etc.
