### ISSUE TITLE
Storage example for php72 says to use dev_appserver.py

### ISSUE THREAD

**Issue by jamescrowley** [GoogleCloudPlatform/php-docs-samples#921]
Your storage example for php72 (https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/storage) says to start the example using

    dev_appserver.py --php_executable=/usr/local/bin/php-cgi --storage_path=/tmp/gs .

but as far as I can tell dev_appserver.py does not support the php72 environment any longer

**Comment by bshaffer** [comment]
Wow, you're right! This was a copy paste error. Thanks for finding this. 

It should just require the GOOGLE_APPLICATION_CREDENTIALS and GOOGLE_STORAGE_BUCKET environment variables to be set, and then you can run it with php's built-in web server 

```
php -S localhost:8080
```
