### ISSUE TITLE
How to set proxy in bucket create?

### ISSUE THREAD

**Issue by getzvnm** [GoogleCloudPlatform/php-docs-samples#924]
Hi ,
Is there any way to set proxy in 
  `$bucket = $this->storage->createBucket($bucketName)`

**Comment by bshaffer** [comment]
Hello!
Can you tell me more what you're trying to do? If you want to set a local proxy (e.g. Charles), you can do it like so:

```php
$storage = new StorageClient([
    'projectId' => $projectId,
    'httpHandler' => Google\Auth\HttpHandler\HttpHandlerFactory::build(
        new GuzzleHttp\Client(['proxy' => 'localhost:8888', 'verify' => false])
    )
]);
```

**Comment by bshaffer** [comment]
Closing due to lack of response. Please open a new issue and provide more clarification if needed!
