### ISSUE TITLE
How to deploy php-docs-samples?

### ISSUE THREAD

**Issue by x-positive** [GoogleCloudPlatform/php-docs-samples#932]
There is only answer how to deploy python project with .yaml files in https://cloud.google.com/shell/docs/quickstart guide. And there is the question - how to deploy PHP project, that no contains any .yaml files?

**Comment by bshaffer** [comment]
Take a look at the [Appengine for PHP Quickstart](https://cloud.google.com/appengine/docs/standard/php7/quickstart) for deploying a PHP app to App Engine. You can also take a look at [Deploying a LAMP stack to Compute Engine](https://cloud.google.com/community/tutorials/setting-up-lamp) if that's what you're looking for.
