### ISSUE TITLE
Cannot initialize Google Cloud Datastore with PHP composer

### ISSUE THREAD

**Issue by ceskhiemle** [GoogleCloudPlatform/php-docs-samples#957]
Hi all,

I am using Google Cloud Datastore with PHP.
I already installed a packpage from Google `"google/cloud-datastore": "^1.10"` but when I initialized DatastoreClient, I received the error message as below:

```
$datastore = new \Google\Cloud\Datastore\DatastoreClient([
	'projectId' => 'mova-footapp'
]);
```

`Uncaught Error: Call to undefined method Google\Cloud\Datastore\Connection\Rest::getApiEndpoint() in /var/www/html/vendor/google/cloud-datastore/src/Connection/Rest.php:46`

Do you guys know how to fix this error?
Thank you very much for helping me.

**Comment by bshaffer** [comment]
Hello! Thank you for reporting your issue. Please file this bug over at [google-cloud-php](https://github.com/googleapis/google-cloud-php/issues/new?template=bug_report.md), as that repository is for client library bugs. This repository is for reporting issues for the samples only.

**Comment by bshaffer** [comment]
It is strange though, as `v1.10` of `google/cloud-datastore` relies on version `1.31` of `google/cloud-core`, and as you can see [here](https://github.com/googleapis/google-cloud-php-core/blob/v1.31.0/src/RestTrait.php#L115), the method `getApiEndpoint` exists in that version of `RestTrait`. 

My guess is some of your dependencies are not up to date, but file an issue with the client library team (and reference this issue in it) to be sure!
