### ISSUE TITLE
Error using sample request for text to speech

### ISSUE THREAD

**Issue by OlegTheHamster** [GoogleCloudPlatform/php-docs-samples#962]
I am trying to setup a sample for text-to-speech request. Service account created, app is authorised, but I am getting this error:

`Fatal error: Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Fail to push limit. in /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/CodedInputStream.php:336 Stack trace: #0 /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/CodedInputStream.php(359): Google\Protobuf\Internal\CodedInputStream->pushLimit(196) #1 /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php(288): Google\Protobuf\Internal\CodedInputStream->incrementRecursionDepthAndPushLimit(196, 0, 0) #2 /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(384): Google\Protobuf\Internal\GPBWire::readMessage(Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FileDescriptorProto)) #3 /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(464): Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag(Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\In in /home/host1680941/vendor/google/protobuf/src/Google/Protobuf/Internal/CodedInputStream.php on line 336`

What should I do?

**Comment by bshaffer** [comment]
Have you tried enabling the `protobuf` PHP extension? [see here](https://pecl.php.net/package/protobuf)

**Comment by bshaffer** [comment]
Can you provide steps to reproduce the issue? I cannot reproduce it by calling the text to speech samples, and this is not a complete stack trace.
