### ISSUE TITLE
Usage without pollUntilComplete ?

### ISSUE THREAD

**Issue by boredom2** [GoogleCloudPlatform/php-docs-samples#968]
Hi there,

I would like to use this SDK without the polling, instead, I want to receive the Results later.
So I skipped the "pollUntilComplete" Method and tried to re-open this Operation later.
I got the Operation ID with $operation->getName();

Later:
```
$client = SpeechClient -> getOperationsClient();
$operation => $client->getOperation($OPERATION-ID)
$result = $operation->getResult();
```

Here, the Code crashed, because the SDK cannot find LongRunningRecognizeMetadata.
I "fixed" that by loading this Class before, so the SDK will find it.
This works, but now, $result is just a String "result".

Can maybe someone point me into the right Direction of how to "re-open" a previous Operation and get the Result Objects?

Thanks!

**Comment by bshaffer** [comment]
Try using `resumeOperation` instead of `getOperationsClient()->getOperation`:

```php
// Start the operation
$operation = $speech->longRunningRecognize($config, $audio);
$operationName = $operation->getName(); // Store for later
// ...

// LATER
$operation = $speech->resumeOperation($operationName);
$operation->pollUntilComplete();
$response = $operation->getResult();
```
