### ISSUE TITLE
pubsub: add sample to demonstrate batch publishing

### ISSUE THREAD

**Issue by hongalex** [GoogleCloudPlatform/php-docs-samples#978]
In https://cloud.google.com/pubsub/docs/publisher#batching, there is no sample demonstrating batch publishing for PHP.

Create a sample for showing the use of [`batchPublisher`](https://github.com/googleapis/google-cloud-php/blob/master/PubSub/src/Topic.php#L469-L530). We will add a comment about running the batch daemon as a note in the docs alongside the sample.

**Comment by hongalex** [comment]
cc @jdpedrie

**Comment by hongalex** [comment]
The region tag used for other languages is:
`pubsub_publisher_batch_settings`

**Comment by jdpedrie** [comment]
@hongalex I'll be working on this this week.
