### ISSUE TITLE
Class 'Facade\Ignition\IgnitionServiceProvider' not found

### ISSUE THREAD

**Issue by einnar82** [GoogleCloudPlatform/php-docs-samples#986]
Specifications

- Laravel 6.0

![image](https://user-images.githubusercontent.com/23412411/68179970-e7454a80-ffcc-11e9-90f7-d7477c2577c7.png)

According to the official [release](https://laravel.com/docs/6.x/releases), Laravel now comes with Ignition. The new error page for Laravel from version 6.0 up. I tried to deploy it in App Engine and access the URL, suddenly it comes with this message.

**Comment by kkls-mike** [comment]
composer remove --dev facade/ignition helped in my case

**Comment by bshaffer** [comment]
Thank you for reporting this! It has been fixed in the tutorial. Thank you!

**Comment by wibin86** [comment]
your composer version maybe over 2.x, change composer version to 1.10 ,the error is disappear
